Rules & CW-20 contract deploy, creating task for cw20 transfer with rules
CronCats/cw-croncat pull request #123
Opened 2022-09-28 00:58 UTC by deveusss

2022-10-06 17:26 UTC, TrevorJTClarke requested changes
Awesome stuff!! Minor changes needed

2022-10-06 17:26 UTC, TrevorJTClarke commented on scripts/local/README.md
> -and see: `v9.0.0`
This should be `v10.0.0` now, FYI. Maybe change to say: `for example: v10.0.0`

2022-10-06 17:26 UTC, TrevorJTClarke commented on scripts/local/README.md
> +Install jq
can this be optional?

2022-10-06 17:26 UTC, TrevorJTClarke commented on scripts/local/simple-payroll.sh
> +SIMPLE_PAYROLL='{
Luvvit!

2022-10-06 17:26 UTC, TrevorJTClarke commented on scripts/local/start-in-docker.sh
> +#Display all data
wow, lots of work here, thank you!

2022-10-06 17:26 UTC, TrevorJTClarke commented on scripts/local/transfer-cw20-with-rules.sh
> +RULES='{
I am so stoked on this!

2022-10-06 17:26 UTC, TrevorJTClarke commented on scripts/local/transfer-cw20-with-rules.sh
> +                }
Can we change to higher? Would like to see it trigger 3+ times. This would only trigger once. So change both the interval & amount.
Could also change the "required_balance" to be the native denom, so it shows how its dynamic.

2022-10-06 17:26 UTC, TrevorJTClarke commented on scripts/uni-3/README.md
> +# Examples
This folder / filename is outdated. Maybe change to `uni-testnet`?

2022-10-06 17:26 UTC, TrevorJTClarke commented on scripts/uni-3/README.md
> +and see: `v9.0.0`
See prev comment on this

2022-10-06 20:32 UTC, deveusss commented on scripts/local/README.md
> +Install jq
yes, they are optional)

2022-10-07 07:05 UTC, Buckram123 approved these changes
Nice

2022-10-07 07:33 UTC, NinoLipartiia approved these changes

2022-10-07 08:21 UTC, merged