Fleet/10 18 22
CronCats/cw-croncat pull request #157
Opened 2022-10-19 08:19 UTC by mikedotexe

don't merge this, just passing the baton on some work, in case it's helpful

2022-10-19 20:05 UTC, Buckram123 requested changes
Hey we good please look into #158!

2022-10-19 20:05 UTC, Buckram123 commented on contracts/cw-croncat/src/manager.rs
> +        }
This is what it causes to fail, if task has not enough balance it falls and revert state here instead of unregistering the task

2022-10-20 15:25 UTC, Buckram123 requested changes
Hey, I guess rust having too many meaning to the keyword `map` :DD

2022-10-20 15:25 UTC, Buckram123 commented on contracts/cw-croncat/src/tasks.rs
> +        Ok(Some(TaskResponse::from(res.unwrap())))
Let's revert it https://doc.rust-lang.org/std/option/enum.Option.html#method.map !
equivalent of
```rust
res.map(Into::into)
```
would be
```rust
match res {
  Some(res) => Some(TaskResponse::from(res)), // same as Some(res.into()) or Some(Into::into(res))
  None => None
}
```
While the equivalent of
```rust
if res.is_none() {
  return Ok(None);
}
Ok(Some(TaskResponse::from(res.unwrap())))
```
would be
```rust
match res {
  None => return Ok(None),
  _ => ()
}
let res2 = match res {
  Some(res) => res,
  None => panic("called `Option::unwrap()` on a `None` value")
}
Ok(Some(TaskResponse::from(res2))))
```

2022-11-07 20:40 UTC, mikedotexe commented
Okay pretty sure we've discussed that we can close this since the useful, worthwhile parts have been incorporated in other PRs

2022-11-08 00:10 UTC, mikedotexe commented
I thought I closed this :)

2022-11-08 00:10 UTC, closed without merging