Stacking rules implementation
CronCats/cw-croncat pull request #176
Opened 2022-10-25 14:23 UTC by Buckram123

Closes #64

- [x]  Implementation and tests inside `cw-rules` contract
- [ ] Test from `cw-croncat` side

2022-10-31 20:32 UTC, mikedotexe requested changes
hey @Buckram123 can we take a look at the linting here pls:

<img width="1016" alt="Screen Shot 2022-10-31 at 1 32 04 PM" src="https://user-images.githubusercontent.com/1042667/199104736-aebb53bf-3e3b-45a1-9879-1db9cc77eb62.png">

And a minor merge conflict 🙏🏼

2022-11-04 17:03 UTC, Buckram123 commented
Implementing #189 here, I need stacking rules for this

2022-11-10 01:29 UTC, mikedotexe commented on contracts/cw-croncat/src/error.rs
> +    #[error("No rules for this task hash: {task_hash}")]
great catch

2022-11-10 01:46 UTC, mikedotexe commented on contracts/cw-rules/Cargo.toml
> +cw-rules-core = { version = "0.1.2", path = "../../packages/cw-rules-core" }
Thank you for being diligent in bumping versions

2022-11-15 18:13 UTC, mikedotexe commented
hey @Buckram123 looks like this was moved out of draft? I know this is a big one, feel free to let us know when we can re-review and the merge conflicts are good 🙏🏼

2022-11-18 17:35 UTC, Buckram123 commented
Currently blocked by wasm-size, have few ideas where I can decrease it, hope it will get through before splitting contract

2022-11-18 17:37 UTC, Buckram123 commented
Currently blocked by wasm-size, have few ideas where I can decrease it, hope it will get through before splitting contract

2022-11-21 02:00 UTC, mikedotexe commented
> Currently blocked by wasm-size, have few ideas where I can decrease it, hope it will get through before splitting contract

Gotcha, thanks! Also, if you get to a point where you think it's worth talking about splitting up the contract now, that's a totally reasonable conversation to have. Maybe we can talk about this as a team soon. Thanks so much for the effort on this, it's seriously exciting. I found myself pacing around my house thinking about how cool this is going to be

2022-11-21 22:02 UTC, Buckram123 commented
update: Heyyy, after few small changes still had to sacrifice query non-critical(likely even redundant) information, but now unblocked, so testing locally and on-chain into opening this PR

2022-11-29 04:53 UTC, mikedotexe reviewed
Would love to chat about this during tomorrow's meeting. This might be one of the most interesting PRs we've had in months.

I left another comment about the indexer crashing, expecting a field, but I'll explain the reason why I wanted to run the indexer on it.. So, I was doing basic tests after deploying, instantiating, creating a task, starting the agent, etc.. And I'm pretty sure the same recurring task that I've been doing for a while (simple payroll to three people) completed much earlier than I expected. I noticed the agent logs being uninteresting (no big blocks of logs, like when it's actively doing payroll) and did a query to show the tasks, and saw there were none. So it must have completed and refunded to the rest to the task creator.

I suspect we need to check the gas on this carefully, and compare it to the `main` branch. Perhaps you can try running it and seeing if you see the same thing.

Here's a messy, but simple payroll bash script. (I'm not even using env vars, just pasting the new contract address every time)

[recurring-payroll.sh.removethispartcuzgithub.log](https://github.com/CronCats/cw-croncat/files/10109829/recurring-payroll.sh.removethispartcuzgithub.log)

2022-11-29 04:53 UTC, mikedotexe commented on contracts/cw-croncat/src/tests/helpers.rs
> +        //funds_withdrawn_recurring: Default::default(),
Hey, curious about this part? Are we removing these to reduce the contract size a bit?
I was trying this out locally and my indexer broke because it's expecting to store values from here.

2022-11-29 13:54 UTC, Buckram123 commented on contracts/cw-croncat/src/tests/helpers.rs
> +        //funds_withdrawn_recurring: Default::default(),
Yeah, needed last few kb to cut :D, here is the comment tho:
https://github.com/CronCats/cw-croncat/blob/6fda939ac75834938775fe59137bf46d47637963/packages/cw-croncat-core/src/types.rs#L317-L318

2022-11-29 18:19 UTC, mikedotexe commented on contracts/cw-croncat/src/tests/helpers.rs
> +        //funds_withdrawn_recurring: Default::default(),
Awesome! Did I understand from today's meeting that you'll remove the field altogether? Making sure

2022-12-01 20:03 UTC, Buckram123 commented on contracts/cw-croncat/src/tests/helpers.rs
> +        //funds_withdrawn_recurring: Default::default(),
Done)

2022-12-03 18:06 UTC, mikedotexe commented on contracts/cw-croncat/src/agent.rs
> +            .map_err(|err| StdError::generic_err(err.to_string()))
good eye

2022-12-03 18:07 UTC, mikedotexe commented on contracts/cw-croncat/src/agent.rs
> +                    unsafe {
interested in hearing about this `unsafe` usage here 🍿

2022-12-03 18:19 UTC, mikedotexe commented on contracts/cw-croncat/src/owner.rs
> +        // let reply_queue: Vec<ReplyQueueResponse> = self
I know this is a pretty big PR, so wanted to make sure we intended to keep these commented out. (IMO commenting out is actually fine at this stage, just want to call it out in case it's helpful and you're like, "oh wait, no we can bring that back actually")

2022-12-05 15:33 UTC, Buckram123 commented on contracts/cw-croncat/src/owner.rs
> +        // let reply_queue: Vec<ReplyQueueResponse> = self
I guess it's fine to keep this field for debugging later, reply queue should always be empty, when we query it, because we clean it up at the and of every proxy_call(also there shouldn't be more than 1 Item too).

2022-12-05 15:38 UTC, Buckram123 commented on contracts/cw-croncat/src/agent.rs
> +                    unsafe {
If we already found agent at N position, we can safely assume that there is at least N agents, so we can safely unwrap an option, and we don't need check, so IMO it's perfect place for `unwrap_unchecked()`

2022-12-05 16:57 UTC, Buckram123 commented
DEMO: https://github.com/Buckram123/cw-croncat/pull/1

2022-12-07 19:50 UTC, TrevorJTClarke approved these changes
love the huggeeeeeee progress on this!! Let's get this out in testnet for further feedback loops :D

2022-12-07 19:50 UTC, TrevorJTClarke commented on packages/cw-croncat-core/src/msg.rs
> +    // pub reply_queue: Vec<ReplyQueueResponse>,
im in agreement, let's remove and remove the comments

2022-12-07 22:37 UTC, mikedotexe approved these changes
Thank you for the demo here, too:
https://github.com/Buckram123/cw-croncat/blob/2cec3d4b9535d28839c47f463679f099f7b731f4/demo/DEMO.md

2022-12-08 22:54 UTC, TrevorJTClarke approved these changes
HERE WE GOOOOOOOOOOO!!!!!

2022-12-08 22:54 UTC, merged