Buckram/update agent status
CronCats/cw-croncat pull request #182
Opened 2022-10-31 16:30 UTC by Buckram123

Closes #181

2022-10-31 20:45 UTC, mikedotexe commented on contracts/cw-croncat/src/agent.rs
> +                let mut active_agents = active_agents;
This makes it mutable?

2022-10-31 20:46 UTC, mikedotexe commented on contracts/cw-croncat/src/helpers.rs
> +    pub(crate) fn max_agent_index(
Could we add a triple-backslash comment here talking about what this method does? 🙏🏼

2022-10-31 20:49 UTC, mikedotexe commented
Hey, thanks for doing this. Sorry, but can we rework this so the first pending agent isn't automatically put into the active queue? We'd still expect agents in the pending queue to be running, and don't want to promote an agent that might not be running anymore. Running agents will be checking to see if they have the `Nominated` status, and as you remember, as time goes on, the next pending agents are allowed to get in first if they're not online and checking.

2022-10-31 20:50 UTC, mikedotexe requested changes
Hey, thanks for doing this. Sorry, but can we rework this so the first pending agent isn't automatically put into the active queue? We'd still expect agents in the pending queue to be running, and don't want to promote an agent that might not be running anymore. Running agents will be checking to see if they have the `Nominated` status, and as you remember, as time goes on, the next pending agents are allowed to get in first if they're not online and checking.

2022-10-31 20:52 UTC, Buckram123 commented on contracts/cw-croncat/src/agent.rs
> +                let mut active_agents = active_agents;
yeah, we can play with mutability of variable if we own it any time
```rust
  // not mutable
  let a = 5;
  // mutable, quick change in close scope
  let mut a = a;
  a = 6;
  // not mutable
  let a = a;
```

2022-10-31 21:00 UTC, Buckram123 commented
> We'd still expect agents in the pending queue to be running, and don't want to promote an agent that might not be running anymore.

If first agent from pending queue is offline and we have tasks to do, isn't it okay to kick him for being not active and move on until we find online agent?

> Running agents will be checking to see if they have the `Nominated` status, and as you remember, as time goes on, the next pending agents are allowed to get in first if they're not online and checking.

I kinda missed the point, right now the timer starts as soon as new task is created, do we want to make first pending agent `Nominated` if active queue is empty even if timer haven't been started yet? @mikedotexe

2022-11-02 20:52 UTC, mikedotexe commented
> I kinda missed the point, right now the timer starts as soon as new task is created, do we want to make first pending agent `Nominated` if active queue is empty even if timer haven't been started yet? @mikedotexe

Let's see… so my understanding is that in the CronCat Manager Config, we have `agent_nomination_begin_time` which gets set every time a new task is added, here:

(this is in the `create_task` function)
https://github.com/CronCats/cw-croncat/blob/8c85201856c3dfa89069b5fe97540c3f0d5ee5fa/contracts/cw-croncat/src/tasks.rs#L373-L374

Maybe we can walk through the scenario you're imagining?

Also, I'm wondering if you're suggesting that right here:
https://github.com/CronCats/cw-croncat/blob/8c85201856c3dfa89069b5fe97540c3f0d5ee5fa/contracts/cw-croncat/src/helpers.rs#L165-L166

We check to see if there's an empty  active queue, and if there is, immediately return `AgentStatus::Nominated`?

2022-11-02 20:55 UTC, Buckram123 commented
> We check to see if there's an empty active queue, and if there is, immediately return `AgentStatus::Nominated`?

Yeah, but only for first agent, for the rest of the agents nomination works as normal

2022-11-02 20:59 UTC, mikedotexe commented
> Yeah, but only for first agent, for the rest of the agents nomination works as normal

Okay, yes, I agree that's good logic to add, thank you!

2022-11-02 21:07 UTC, mikedotexe commented on contracts/cw-croncat/src/helpers.rs
> +        if active.is_empty() && agent_position == 0 {
Oh i see you added it here 👍🏼

2022-11-02 21:10 UTC, mikedotexe commented on contracts/cw-croncat/src/tests/agent.rs
> +fn test_last_unregistered_active_agent_promotes_first_pending() {
Thank you for adding this test!

2022-11-03 16:35 UTC, mikedotexe approved these changes

2022-11-03 16:35 UTC, merged