Migrate pending queue to deque
CronCats/cw-croncat pull request #185
Opened 2022-11-03 21:25 UTC by Buckram123

Closes #183

2022-11-08 00:12 UTC, mikedotexe commented on contracts/cw-croncat/src/owner.rs
> +                .take(50)
I think this will work for now, eventually we'd like to have pagination, but don't feel it's going to get past 50 pending agents for a while, and likely not critical to know about all of them anyway

2022-11-08 00:12 UTC, mikedotexe commented on contracts/cw-croncat/src/state.rs
> +    pub agent_pending_queue: Deque<'a, Addr>,
Good find with the Deque!

2022-11-08 00:13 UTC, mikedotexe commented on contracts/cw-croncat/src/tests/agent.rs
> +fn removing_agent_from_any_side_is_working() {
Again, really appreciate you adding tests with these

2022-11-08 00:17 UTC, mikedotexe requested changes
(just that explanation of `from_behind` since I'm not seeming to understand it yet)

2022-11-08 00:17 UTC, mikedotexe commented on contracts/cw-croncat/src/agent.rs
> +    /// In case it fails to unregister pending agent try to set `from_behind` to true
@Buckram123 would you mind taking a little time to help me understand the `from_behind` idea? If it's easy to do here, that's great, or if it's better to explain on our next call, that works, too

2022-11-08 00:38 UTC, Buckram123 commented on contracts/cw-croncat/src/agent.rs
> +    /// In case it fails to unregister pending agent try to set `from_behind` to true
Hey, thanks for asking!
In short: there is a slight chance, that removing an agent could be impossible from left to right, so agent could try to remove himself from right to left.
In shorter: Gas.

2022-11-08 00:42 UTC, Buckram123 commented on contracts/cw-croncat/src/owner.rs
> +                .take(50)
Honestly, I would like to separate query of pending/active agents queues from this method, to have an easier time for pagination

2022-11-09 19:25 UTC, mikedotexe approved these changes

2022-11-09 19:25 UTC, merged