[FEATURE] Add "simulate" query msg for estimating gas & occurrences
CronCats/cw-croncat pull request #209
Opened 2022-12-10 00:17 UTC by deveusss

closes #204

2022-12-10 00:19 UTC, TrevorJTClarke commented on packages/cw-croncat-core/Cargo.toml
> +version = "0.1.4"
🚀

2022-12-15 17:59 UTC, Buckram123 requested changes
Nice, few small changes, please check https://github.com/CronCats/cw-croncat/issues/204#issuecomment-1353468289
Let's do some testing as well!

2022-12-15 17:59 UTC, Buckram123 commented on contracts/cw-croncat/src/tasks.rs
> +        .unwrap();
Let's have useful error if something failed during validation!
```suggestion
        .map_err(|e| cosmwasm_std::StdError::generic_err(e.to_string()))?;
```

2022-12-15 17:59 UTC, Buckram123 commented on packages/cw-croncat-core/src/types.rs
> +    let boundary = BoundaryValidated::validate_boundary(task.boundary, &interval).unwrap();
```suggestion
    let boundary = BoundaryValidated::validate_boundary(task.boundary, &interval)?;
```
Let's include useful error!

2022-12-15 17:59 UTC, Buckram123 commented on packages/cw-croncat-core/src/types.rs
> +            let mut start_block: u64 = boundary.start.unwrap();
```suggestion
            let mut start_block: u64 = boundary.start.unwrap_or(env.block.height);
```
I guess instead of panic we want some default value here?

2022-12-15 17:59 UTC, Buckram123 commented on packages/cw-croncat-core/src/types.rs
> +            let mut start_time: u64 = boundary.start.unwrap();
```suggestion
            let mut start_time: u64 = boundary.start.unwrap_or(env.block.height);
```

2022-12-15 17:59 UTC, Buckram123 commented on packages/cw-croncat-core/src/types.rs
> +                    end_time = boundary.end.unwrap();
```suggestion
                    end_time = end;
```

2022-12-15 18:10 UTC, deveusss commented on scripts/update-checksum-m1.sh
> +cat artifacts/checksums.txt | grep -e cw_croncat-aarch64.wasm -e cw_rules-aarch64.wasm > checksum
yes

2022-12-15 18:10 UTC, deveusss commented on packages/cw-croncat-core/examples/schema.rs
> +    );
Its used in client side

2022-12-15 18:47 UTC, TrevorJTClarke requested changes
This is looking great @deveusss!!
Would like to see the addition of task_hash from comment in #204 then i think we're GTG

2022-12-16 19:39 UTC, TrevorJTClarke requested changes
Unfortunately this work is blocked until task calc is ready.

2022-12-16 19:39 UTC, TrevorJTClarke commented on packages/cw-croncat-core/src/types.rs
> +pub fn simulate_task(
hey @deveusss this is looking great - thanks for adding `task_hash` on response.

Based on today's discussion, i believe we must wait for the core config+computation changes before adjusting this logic for new task calculator.
Let's resume once thats ready/merged

2022-12-22 18:25 UTC, TrevorJTClarke commented
NOTE: I think we're ready to resume work on this PR, however after doing my own simulations on website, there are several loose ends in this implementation that needs fixes. Will need discuss details

2023-01-17 00:01 UTC, TrevorJTClarke commented
hey @deveusss @NinoLipartiia -- i know this is horrendous to pick through, but here's the huge list of things needed in simulation:

* Start: https://github.com/CronCats/catgrass-ui/blob/development/src/components/forms/RecipeSummary.vue#L151-L295
* Helper occur: https://github.com/CronCats/catgrass-ui/blob/development/src/stores/taskCreator.ts#L28
* Helper boundary: https://github.com/CronCats/catgrass-ui/blob/development/src/stores/taskCreator.ts#L9

I think we should plot the list of required checks & OOP for this method to be efficient.

2023-01-21 22:36 UTC, Buckram123 commented
@NinoLipartiia oops, exceeded size limit, I guess?)

2023-01-23 12:46 UTC, NinoLipartiia commented
> 

Yes, wasm size is 834 KB
I guess it's fine for now, can't see how to optimize it

2023-01-23 13:28 UTC, deveusss commented
> > 
> 
> Yes, wasm size is 834 KB I guess it's fine for now, can't see how to optimize it

so can't deploy with that size?

2023-01-23 14:30 UTC, NinoLipartiia commented
It seems like testnet is down, so I'm not sure if the problem is wasm size

2023-01-23 22:10 UTC, TrevorJTClarke commented on packages/cw-croncat-core/src/types.rs
> +    if task_info.with_queries() {
This isn't quite ideal here - it actually falls into the category of needing to check how many occur for funds.

2023-01-23 22:12 UTC, TrevorJTClarke requested changes
I have not confirmed all the logic here, but after quick review there are a couple places needing confirmation of desired logic. This function was needed for website & vectis, but after web got the functionality, id like to pause this PR until we're post-audit so we can appropriately revisit with fresh eyes. Blocking for now.

2023-03-23 21:22 UTC, closed without merging