[FIX]: create_task response data
CronCats/cw-croncat pull request #216
Opened 2022-12-14 22:13 UTC by deveusss

closes #207

2022-12-15 15:05 UTC, Buckram123 requested changes
small fix

2022-12-15 15:05 UTC, Buckram123 commented on contracts/cw-croncat/src/tasks.rs
> +            .set_data(format!("task_hash {}", hash).into_bytes())
```suggestion
            .set_data(hash.as_bytes())
```
I think should work

2022-12-16 15:59 UTC, Buckram123 commented on contracts/cw-croncat/src/tasks.rs
> +            .set_data(format!("task_hash {}", hash).into_bytes())
Oops, just noticed that there is also "task_hash" string as well) Anyway do we want to format it in some different way?

2022-12-16 19:33 UTC, TrevorJTClarke requested changes

2022-12-16 19:33 UTC, TrevorJTClarke commented on contracts/cw-croncat/src/contract.rs
> -            QueryMsg::GetTaskHash { task } => to_binary(&self.query_get_task_hash(*task)?),
Hey @deveusss, im not happy with removing this. Do you see duplicated way of getting task hash? External integrations (web, etc) should be able to compute tash hash with query, so we have a reliable way without additional libs or self-compute that could be innacurate.
If this isn't duplicated, we need to keep this as the website uses it.

2022-12-16 19:49 UTC, Buckram123 commented on contracts/cw-croncat/src/contract.rs
> -            QueryMsg::GetTaskHash { task } => to_binary(&self.query_get_task_hash(*task)?),
@TrevorJTClarke I think it's still supposed to be removed in #209 right?

2022-12-16 20:05 UTC, TrevorJTClarke commented on contracts/cw-croncat/src/contract.rs
> -            QueryMsg::GetTaskHash { task } => to_binary(&self.query_get_task_hash(*task)?),
I dont think so - adding simulate is different use case thank just purely getting task_hash. 
Having tash_hash part of simulate is def a nice thing!

2022-12-17 00:27 UTC, deveusss commented on contracts/cw-croncat/src/contract.rs
> -            QueryMsg::GetTaskHash { task } => to_binary(&self.query_get_task_hash(*task)?),
brought GetTaskHash back

2022-12-17 17:08 UTC, mikedotexe commented on contracts/cw-croncat/src/tasks.rs
> +            .set_data(format!("task_hash {}", hash).into_bytes())
Curious why we're not using `.add_attribute` here, @deveusss? 

![Uploading Screen Shot 2022-12-17 at 9.07.54 AM.png…]()

2022-12-17 19:42 UTC, deveusss commented on contracts/cw-croncat/src/tasks.rs
> +            .set_data(format!("task_hash {}", hash).into_bytes())
@mikedotexe  image is not loading)

2022-12-17 19:51 UTC, deveusss commented on contracts/cw-croncat/src/tasks.rs
> +            .set_data(format!("task_hash {}", hash).into_bytes())
@mikedotexe The reason is the consumer, like vectis, could get data from events

2022-12-17 22:02 UTC, mikedotexe approved these changes

2022-12-17 22:05 UTC, TrevorJTClarke approved these changes

2022-12-17 22:08 UTC, TrevorJTClarke requested changes

2022-12-17 22:08 UTC, TrevorJTClarke commented on contracts/cw-croncat/src/tasks.rs
> +            .set_data(format!("task_hash {}", hash).into_bytes())
@deveusss i still see format! in there, can you change to only hash? don't want vectis or others having to string split `task_hash jfdiksajfkldsjfdkslajf`

2022-12-17 22:28 UTC, deveusss commented on contracts/cw-croncat/src/tasks.rs
> +            .set_data(format!("task_hash {}", hash).into_bytes())
thank you, done)

2022-12-17 22:38 UTC, TrevorJTClarke approved these changes

2022-12-17 23:04 UTC, merged