fix: remove unused scripts and add optiomization for m1
CronCats/cw-croncat pull request #224
Opened 2022-12-18 15:54 UTC by deveusss

closes #173

2022-12-20 15:03 UTC, Buckram123 requested changes
Nice to have additional functionality for m1 users!

2022-12-20 15:03 UTC, Buckram123 commented on scripts/uni-testnet/start.sh
> +just build
Do we want to build it twice?
```suggestion
```
Optimizer rebuilds it before optimizing!

2022-12-20 20:54 UTC, deveusss commented on justfile
> +
optimize-rs a way faster then workspace one

2022-12-21 12:54 UTC, Buckram123 commented on justfile
> +
https://github.com/CosmWasm/rust-optimizer/blob/main/README.md#contracts-as-workspace-members
>Sometime you want many contracts to be related and import common functionality. This is exactly the case of [cosmwasm-plus](https://github.com/CosmWasm/cosmwasm-plus). In such a case, we can often not just compile from root, as the compile order is not deterministic and there are feature flags shared among the repos. This has lead to https://github.com/CosmWasm/rust-optimizer/issues/21.

Lets remove `optimize-rs` and `optimize-rs-m1`, to make sure it won't get used and to avoid issues mentioned here, sorry :fearful:

2022-12-21 17:06 UTC, mikedotexe commented on justfile
> +
good eye, I think I'm in favor of removing. hey, I learned something!

2022-12-21 17:09 UTC, mikedotexe commented
@deveusss looks like there's a minor merge conflict after merging a couple of your other amazing PRs))

2022-12-22 01:05 UTC, merged