[FEATURE]: Create commit hooks for build, test, checksum update and optimisation on commit #223
CronCats/cw-croncat pull request #226
Opened 2022-12-18 20:35 UTC by deveusss

closes #223

2022-12-19 12:48 UTC, Buckram123 requested changes
Nice to have this cool tool!

2022-12-19 12:48 UTC, Buckram123 commented on justfile
> +all: build test lint schema gen optimize checksum
Let's have lint before builds and tests!
```suggestion
all: lint build test schema gen optimize checksum
```

2022-12-19 12:48 UTC, Buckram123 commented on packages/cw-croncat-core/Cargo.toml
> +rusty-hook = "0.11.2"
Let's have new lines at the end of the files)
```suggestion
rusty-hook = "0.11.2"

```

2022-12-19 12:48 UTC, Buckram123 commented on packages/cw-rules-core/Cargo.toml
> +rusty-hook = "0.11.2"
```suggestion
rusty-hook = "0.11.2"

```

2022-12-19 12:48 UTC, Buckram123 commented on contracts/cw-rules/Cargo.toml
> +rusty-hook = "0.11.2"
```suggestion
rusty-hook = "0.11.2"

```

2022-12-19 12:48 UTC, Buckram123 commented on contracts/cw-croncat/Cargo.toml
> +rusty-hook = "0.11.2"
```suggestion
rusty-hook = "0.11.2"

```

2022-12-19 12:48 UTC, Buckram123 commented on Cargo.toml
> +overflow-checks = true
```suggestion
overflow-checks = true

```

2022-12-19 12:48 UTC, Buckram123 commented on .rusty-hook.toml
> +pre-commit = "just all"
I often do few commits before pushing. Is that's enough for pre-commit?
```suggestion
pre-commit = "just lint test"
pre-push = "just all"
```

2022-12-19 16:58 UTC, deveusss commented on justfile
> +all: build test lint schema gen optimize checksum
this one is fixed in one of PRs))

2022-12-20 20:04 UTC, Buckram123 approved these changes

2022-12-21 17:07 UTC, mikedotexe commented on justfile
> +lint:
👍🏼

2022-12-21 17:08 UTC, mikedotexe approved these changes

2022-12-21 17:09 UTC, merged