[FIX]: Optimiser bug "does not match the specified platform"
CronCats/cw-croncat pull request #242
Opened 2022-12-22 20:10 UTC by deveusss

2022-12-23 18:09 UTC, Buckram123 requested changes

2022-12-23 18:09 UTC, Buckram123 commented on justfile
>  		cosmwasm/workspace-optimizer:0.12.8
shouldn't it be ?
```
cosmwasm/workspace-optimizer-arm64
```

2022-12-23 18:13 UTC, deveusss commented on justfile
>  		cosmwasm/workspace-optimizer:0.12.8
DANGER
There is an [rust-optimizer-arm64](https://hub.docker.com/r/cosmwasm/rust-optimizer-arm64) docker builder image that gives faster output on Apple M1 chip. Arm images are released to ease development and testing on Mac M1 machines. The native Arm version produces different wasm artifacts than the Intel version. For release / production use, only contracts built with the Intel optimizers must be used.

2022-12-23 18:16 UTC, Buckram123 commented on justfile
>  		cosmwasm/workspace-optimizer:0.12.8
> DANGER There is an [rust-optimizer-arm64](https://hub.docker.com/r/cosmwasm/rust-optimizer-arm64) docker builder image that gives faster output on Apple M1 chip. Arm images are released to ease development and testing on Mac M1 machines. The native Arm version produces different wasm artifacts than the Intel version. For release / production use, only contracts built with the Intel optimizers must be used.

We're not planning to deploy m1 wasm files, it's only for testing, right? Or what's the purpose of `optimize-m1` command then?

2022-12-23 18:22 UTC, deveusss commented on justfile
>  		cosmwasm/workspace-optimizer:0.12.8
for testing localy

2022-12-23 18:25 UTC, Buckram123 commented on justfile
>  		cosmwasm/workspace-optimizer:0.12.8
@deveusss but rust ones using arm64 image https://github.com/CronCats/cw-croncat/blob/7c7230d889a170a9c194c654689efb2eb0667e5e/justfile#L59-L69

2022-12-23 18:27 UTC, Buckram123 commented on justfile
>  		cosmwasm/workspace-optimizer:0.12.8
and i'm still leaning towards removing the rust ones https://github.com/CronCats/cw-croncat/pull/224#discussion_r1054357410

2023-01-09 22:30 UTC, deveusss commented on justfile
>  		cosmwasm/workspace-optimizer:0.12.8
@Buckram123 what does it mean, rust optimiser can use **arm** ones

2023-01-09 23:31 UTC, merged