Update mod-nft
CronCats/cw-croncat pull request #248
Opened 2023-01-05 21:11 UTC by NinoLipartiia

Created a separate contract for nft rules.
Added `AddrHasNft`, which checks if the address has any tokens on this `nft_contract`.

Also according to [this documentation](https://github.com/CronCats/cw-croncat/wiki/%E2%9A%99%EF%B8%8F-Rules-Architecture#nft-rules) there should be two more queries, which check if `token_id` doesn't have owner. But i think `owner` [is not optional](https://github.com/CosmWasm/cw-nfts/blob/c7be7aba9fb270abefee5a3696be62f2736592a0/contracts/cw721-base/src/state.rs#L105) for tokens. Could you please explain how these queries should work?

2023-01-06 16:17 UTC, Buckram123 requested changes
Nice progress! Small nits

2023-01-06 16:17 UTC, Buckram123 commented on contracts/mod-nft/src/contract.rs
> +    Err(ContractError::Noop)
```suggestion
    Err(ModError::Noop)
```
Do we want to move that to the `mod-sdk` package? Every mod will have only this one error

2023-01-06 16:17 UTC, Buckram123 commented on contracts/mod-nft/src/error.rs
>      Std(#[from] StdError),
```suggestion
```
It can't return StdError, since we don't check anything

2023-01-06 16:17 UTC, Buckram123 commented on contracts/mod-nft/src/msg.rs
> +    },
Don't you mind adding short descriptions to the enum variants?

2023-01-06 16:17 UTC, Buckram123 commented on contracts/mod-nft/src/contract.rs
> +        data: Default::default(),
I think returning tokens might be useful here!
So we can avoid another query of list of nfts :)

2023-01-06 16:17 UTC, Buckram123 commented on contracts/mod-nft/src/contract.rs
> +            limit: None,
Thinking if we should add limit here. I know default limit should be covered by the cw721 itself, but what if it fails?

Note: if we consider to not return tokens, we want it to be exactly "1"

2023-01-06 16:17 UTC, Buckram123 commented on contracts/mod-nft/src/contract.rs
> +            include_expired: None,
Can this field be useful in any way?

2023-01-06 16:28 UTC, Buckram123 commented on contracts/mod-nft/Cargo.toml
>  [dev-dependencies]
```suggestion
mod-sdk = { workspace = true }
thiserror = { workspace = true }

[dev-dependencies]
cw721-base = { workspace = true }
cw-multi-test = { workspace = true }
```
Missed last thing

2023-01-06 19:16 UTC, NinoLipartiia commented on contracts/mod-nft/src/contract.rs
> +    Err(ContractError::Noop)
Do you think we should move `ContractError` to `mod-sdk` and include only the error about `execute`?

2023-01-06 19:23 UTC, Buckram123 commented on contracts/mod-nft/src/contract.rs
> +    Err(ContractError::Noop)
> Do you think we should move `ContractError` to `mod-sdk` and include only the error about `execute`?

I like the idea, but I'm not sure) We should call it something like `ModError` instead if we do so

2023-01-09 11:43 UTC, NinoLipartiia commented on contracts/mod-nft/src/error.rs
>      Std(#[from] StdError),
But we still can get `StdError` inside queries, can't we?

2023-01-09 13:23 UTC, Buckram123 approved these changes
Good job on cleaning up!

2023-01-09 13:23 UTC, Buckram123 commented on contracts/mod-nft/src/contract.rs
> +use cosmwasm_std::{entry_point, to_binary, StdError};
```suggestion
#[cfg(not(feature = "library)
use cosmwasm_std::entry_point;
use cosmwasm_std::{to_binary, StdError};
```
Just to be safe!

2023-01-09 13:23 UTC, Buckram123 commented on contracts/mod-nft/src/lib.rs
> +pub mod types;
```suggestion
pub mod types;

pub use mod_sdk::error::ModError as ContractError;
```
Sorry for this :D Let's be consistent and call it as `ContractError` and make it public inside `lib.rs`

2023-01-09 13:23 UTC, Buckram123 commented on contracts/mod-nft/src/tests/has_nft.rs
> +    assert_eq!(res.data, to_binary::<std::vec::Vec<String>>(&vec![])?);
Thanks for testing data!

Funny you had to do that cast

2023-01-11 22:11 UTC, TrevorJTClarke approved these changes
Looks solid @NinoLipartiia!!
Minor nit pick on naming convention, otherwise GTG!! ✨

2023-01-11 22:11 UTC, TrevorJTClarke commented on contracts/mod-nft/src/contract.rs
> +/// Query: OwnerOfNft
I think this naming might be confusing. Since the condition is `owns any`, can we change to be `OwnerHasNft` or `OwnerNfts`

2023-01-11 22:11 UTC, TrevorJTClarke commented on contracts/mod-nft/src/contract.rs
> +/// Data is empty
Could we optionally return the nft holdings? Could be rad for future transforms

2023-01-12 14:46 UTC, NinoLipartiia commented on contracts/mod-nft/src/contract.rs
> +/// Query: OwnerOfNft
@TrevorJTClarke  `OwnerOfNft` checks whether `address` is the owner of particular nft, so I think `OwnerHasNft` sounds more confusing.

`Owns any` is the condition for `AddrHasNft`, it checks if `address` has at least one nft

2023-01-12 19:01 UTC, TrevorJTClarke commented on contracts/mod-nft/src/contract.rs
> +/// Query: OwnerOfNft
Its just a simple typo i think -- its a copy/paste from above

2023-01-12 19:02 UTC, merged