Tests for mod-balances
CronCats/cw-croncat pull request #249
Opened 2023-01-05 21:15 UTC by NinoLipartiia

2023-01-06 16:27 UTC, Buckram123 approved these changes
Good job, few fixes and LGTM

2023-01-06 16:27 UTC, Buckram123 commented on contracts/mod-balances/Cargo.toml
>  [dev-dependencies]
```suggestion
mod-sdk = { workspace = true }
thiserror = { workspace = true }

[dev-dependencies]
cw20-base = { workspace = true }
cw-multi-test = { workspace = true }
cw-utils = { workspace = true }
```
We don't test dependencies to be included outside tests

2023-01-06 16:27 UTC, Buckram123 commented on contracts/mod-balances/src/msg.rs
>      HasBalanceComparator(HasBalanceComparator),
Let's add small descriptions to enum variants!

2023-01-06 16:27 UTC, Buckram123 commented on contracts/mod-balances/src/tests/balance_comparator.rs
> +    assert_eq!(res.data, to_binary(&Uint128::new(1_000_000)).unwrap());
Thanks for testing `QueryResponse.data`!

2023-01-11 22:00 UTC, TrevorJTClarke requested changes
Hey @NinoLipartiia this is looking awesome!!
Left a couple comments on tests cov missing, minor things.

I think i made a big mistake on ergonomics as well.
The comparison is backwards, so for example the logic is currently:
`required_balance <= balance` 
which feels wrong, i believe it needs to be this for all of them:
`balance <= required_balance`
So when integrating, the user specifying Lte, expects the balance to fluctuate and the requirement to stay consistent.

Happy to chat on that if it doesn't make sense.

2023-01-11 22:00 UTC, TrevorJTClarke commented on contracts/mod-balances/src/tests/balance_comparator.rs
> +    assert_eq!(res.data, to_binary(&Uint128::new(1_000_000)).unwrap());
Need a passing test for `Lt` after this

2023-01-11 22:00 UTC, TrevorJTClarke commented on contracts/mod-balances/src/tests/balance_comparator.rs
> +}
Same as with Native, needs coverage of `Gt` & `Gte`

2023-01-13 00:14 UTC, TrevorJTClarke approved these changes
YEAHHHHHHHHHH

2023-01-13 00:15 UTC, merged