croncat-manager split
CronCats/cw-croncat pull request #250
Opened 2023-01-06 14:56 UTC by Buckram123

After `tasks` and `agents` split done

TODO: finish `proxy_call()`, `tick()` and `schema`

2023-01-06 15:04 UTC, Buckram123 commented on contracts/croncat-manager/src/balances.rs
> +    let msg: ReceiveMsg = from_binary(&wrapper.msg)?;
Noticed that everyone uses `ReceiveMsg` even if it's empty. I guess it's better to be sure why user sent tokens here. 
https://github.com/CosmWasm/cw-plus/blob/4da476f9e426fb87689b6f0c3398ff08a65248d1/contracts/cw4-stake/src/msg.rs#L42-L48

2023-01-06 15:06 UTC, Buckram123 commented on contracts/croncat-manager/src/balances.rs
> +                .add_attribute("action", "receive_cw20")
all attributes in execute and instantiate methods 
```json
{"key": "method", "value": "method_name"}
```
replaced by
```json
{"key": "action", "value": "method_name"}
```

2023-01-06 15:08 UTC, Buckram123 commented on contracts/croncat-manager/src/contract.rs
> +        // TODO?:.add_attribute("config", format!("{:?}, &config"))
We have too many config items, should we pack them in single attribute? What's your thoughts?

2023-01-06 15:11 UTC, Buckram123 commented on contracts/croncat-manager/src/msg.rs
> +    Config {},
`GetQueryMethod`, renamed to the `QueryMethod`

2023-01-06 15:28 UTC, Buckram123 commented
Should I add in here minimal factory contract, that will instantiate all of the contract and just store addresses of contracts?

2023-01-06 17:24 UTC, Buckram123 commented on packages/croncat-sdk-core/src/types.rs
> +}
This struct had field `native_denom`, I believe it should be gathered from the config instead

2023-01-11 23:54 UTC, TrevorJTClarke commented on contracts/croncat-manager/src/contract.rs
> +        // TODO?:.add_attribute("config", format!("{:?}, &config"))
Honestly probably not. Can use a query for that later

2023-01-18 18:12 UTC, TrevorJTClarke requested changes
This is great progress!! left a few changes below :)

2023-01-18 18:12 UTC, TrevorJTClarke commented on contracts/croncat-manager/src/contract.rs
> +        ExecuteMsg::WithdrawCw20WalletBalances { cw20_amounts } => {
Is this only for users or agents? Let's make it super obvious: `UserWithdraw` or `TaskBalanceWithdraw` or `AgentWithdraw`

2023-01-18 18:12 UTC, TrevorJTClarke commented on contracts/croncat-manager/src/contract.rs
> +    // TODO: execute task
Assuming TBD ;)

2023-01-18 18:16 UTC, Buckram123 commented on contracts/croncat-manager/src/balances.rs
> +        let new_avail_bal = sub_available_cw20(deps.storage, cw20)?;
https://github.com/CronCats/cw-croncat/blob/31bef0f969ae236bce868ec2817f2e29e4080f2d/contracts/croncat-manager/src/balances.rs#L119

Don't worry it's covered! It will return overflow error!

2023-01-18 18:20 UTC, Buckram123 commented on contracts/croncat-manager/src/balances.rs
> +    address: String,
So the available balances used only for treasuries, right? This whole time I thought it was a combine of all balances we have, my bad! We don't have treasury_fee implemented yet tho. Should we rename it to the `TREASURY_NATIVE_BALANCE` and `TREASURY_CW20_BALANCE`?

2023-01-18 18:20 UTC, Buckram123 commented on contracts/croncat-manager/src/balances.rs
> +// pub(crate) fn add_agent_native(
> remove if not-needed?

It will be needed

2023-01-18 18:21 UTC, Buckram123 commented on contracts/croncat-manager/src/balances.rs
> +        .add_messages(cw20_messages))
What do you mean by that @TrevorJTClarke

2023-01-18 18:24 UTC, Buckram123 commented on contracts/croncat-manager/src/state.rs
> +pub const USERS_BALANCES_CW20: Map<(&Addr, &Addr), Uint128> = Map::new("users_balances_cw20");
Yes, we can't avoid storing it, unless we are okay to transfer balances from `tasks` contract

2023-01-18 18:28 UTC, TrevorJTClarke commented on contracts/croncat-manager/src/balances.rs
> +    address: String,
That's a good thought. So to be 100% clear, we have 3 buckets of funds:
1. Agent rewards (base compensation for task fee, additional fee for profit)
2. Deposit funds (task funds to be used for compensation)
3. Owner/Treasury funds (balances earned to DAO similar to agent)

I am just hoping the implementation is extremely obvious with where allocation of funds are

2023-01-18 18:28 UTC, Buckram123 commented on packages/croncat-sdk-core/src/types.rs
> +    // pub treasury_id: Option<Addr>,
We don't have it in our `main` branch, is there any requirements i can look at?

2023-01-18 18:29 UTC, TrevorJTClarke commented on contracts/croncat-manager/src/balances.rs
> +        .add_messages(cw20_messages))
so if response having empty vec messages, does it remove gas if we just start a mut response over the logic of this function? or am i crazy

2023-01-18 18:32 UTC, TrevorJTClarke commented on packages/croncat-sdk-core/src/types.rs
> +    // pub treasury_id: Option<Addr>,
the main has history from june when i did it and then pulled out :P 

Its pretty simple really:
IF treasury_id (or really `treasury_addr`) then any DAO fees/rewards can be withdrawn to the `treasury_addr`.
If NO `treasury_addr` on config, then withdraw goes to the `config.owner_id`

2023-01-18 18:33 UTC, TrevorJTClarke commented on contracts/croncat-manager/src/state.rs
> +pub const USERS_BALANCES_CW20: Map<(&Addr, &Addr), Uint128> = Map::new("users_balances_cw20");
okay!! maybe just need to change name to be `temp` or similar

2023-01-18 18:36 UTC, Buckram123 commented on contracts/croncat-manager/src/balances.rs
> +        .add_messages(cw20_messages))
There will be at least 1 message of `bank_msg`, if `cw20_messages` will be empty it will just do nothing

2023-01-19 13:31 UTC, Buckram123 commented on contracts/croncat-manager/src/helpers.rs
> +) -> Result<(), ContractError> {
> Would this be better in packages?

I thought that we try to keep all contracts logic inside contract crate, unless it's a type logic?

2023-01-19 17:29 UTC, Buckram123 commented on packages/croncat-sdk-core/src/types.rs
> +    // pub treasury_id: Option<Addr>,
@TrevorJTClarke what's our treasury_fees then?

2023-01-19 17:31 UTC, TrevorJTClarke commented on packages/croncat-sdk-core/src/types.rs
> +    // pub treasury_id: Option<Addr>,
@Buckram123 we will need to have same setup to agent fee - for now create a separate configurable variable, but it can be set to same value as agent

2023-01-19 17:33 UTC, TrevorJTClarke commented on contracts/croncat-manager/src/helpers.rs
> +) -> Result<(), ContractError> {
Interesting, good point. So its interesting, we could actually have some package for helpers/utils similar to: https://github.com/DA0-DA0/dao-contracts/blob/main/packages/cw-paginate/src/lib.rs

2023-01-19 17:39 UTC, TrevorJTClarke requested changes

2023-01-19 17:39 UTC, TrevorJTClarke commented on contracts/croncat-manager/src/contract.rs
> +        ExecuteMsg::UserWithdraw {
TY!

2023-01-19 17:39 UTC, TrevorJTClarke commented on packages/croncat-sdk-core/src/msg.rs
> +    OwnerWithdraw {
I still think it should not accept args at all, withdraw the whole amount

2023-01-19 17:42 UTC, Buckram123 commented on contracts/croncat-manager/src/contract.rs
> +fn execute_refill_native_balance(
@TrevorJTClarke oops, need to take a better name for refilling `temp` users, any ideas?

2023-01-19 17:44 UTC, Buckram123 commented on packages/croncat-sdk-core/src/msg.rs
> +    OwnerWithdraw {
> I still think it should not accept args at all, withdraw the whole amount

Just to be clear, this method for withdrawing treasuries only, right? So it only should withdraw single native coin?

2023-01-19 17:56 UTC, TrevorJTClarke commented on packages/croncat-sdk-core/src/msg.rs
> +    OwnerWithdraw {
It should get called by owner (the DAO) with no args, and withdraw ALL funds available, both native, cw20, etc

2023-01-19 18:05 UTC, Buckram123 commented on packages/croncat-sdk-core/src/msg.rs
> +    OwnerWithdraw {
> It should get called by owner (the DAO) with no args, and withdraw ALL funds available, both native, cw20, etc

By "available" what do you mean? Tasks balances/agents rewards gets stolen too?

2023-01-21 03:15 UTC, mikedotexe commented on contracts/croncat-manager/src/contract.rs
> +// TODO: It might be not possible to deserialize all of the active agents, need to find better solution
We talked about a few options in today's meeting, but felt that we could set some sane limit for our early versions.

How's a limit of 5,000 agents sound?

2023-01-21 03:18 UTC, mikedotexe commented on contracts/croncat-manager/src/helpers.rs
> +) -> Result<(), ContractError> {
This is a pretty small function, and since it needs to load the config, feels like it's fine to have here imo

2023-01-21 03:22 UTC, Buckram123 commented on contracts/croncat-manager/src/contract.rs
> +// TODO: It might be not possible to deserialize all of the active agents, need to find better solution
> How's a limit of 5,000 agents sound?

How do we predict gas costs with such big limit? Should we add some gas_fee for each active_agent?

2023-01-21 03:25 UTC, Buckram123 commented on contracts/croncat-manager/src/helpers.rs
> +) -> Result<(), ContractError> {
@mikedotexe I guess it could make sense to make a shared trait ConfigChecker or something like that, but yeah, it's ok to keep it here, at least for now imo :)

2023-01-23 10:58 UTC, deveusss commented
Very cool update!

2023-01-23 21:56 UTC, TrevorJTClarke requested changes
Hey @Buckram123 lookin great! Thank you for the latest changes, esp for treasury support.

One bigger question: How are we handling things if a user/contract simply sends (bank send) to the manager contract? would treasury be able to withdraw, or is it essentially locked?

2023-01-23 21:56 UTC, TrevorJTClarke commented on contracts/croncat-manager/src/balances.rs
> +            // TODO: check if sender is task_owner
Def need to finish this TODO before I feel good merging

2023-01-23 21:56 UTC, TrevorJTClarke commented on contracts/croncat-manager/src/balances.rs
> +            // TODO: check if sender is task_owner
Is this waiting on the tasks contract impl? If so, it shouldn't change msg right, so we can utilize the previous msg here?

2023-01-23 21:56 UTC, TrevorJTClarke commented on contracts/croncat-manager/src/balances.rs
> +    // TODO: check if sender is task_owner
here too please!

2023-01-23 21:56 UTC, TrevorJTClarke commented on contracts/croncat-manager/src/balances.rs
> +    let address = config.treasury_addr.unwrap_or(config.owner_addr);
thank you!

2023-01-23 21:56 UTC, TrevorJTClarke commented on contracts/croncat-manager/src/balances.rs
> +    // TODO: query tasks to check it's task owner who refills
here please :)

2023-01-23 21:56 UTC, TrevorJTClarke commented on contracts/croncat-manager/src/balances.rs
> +                .ibc_coin
is this new?

2023-01-23 21:56 UTC, TrevorJTClarke commented on contracts/croncat-manager/src/contract.rs
> +    let owner_addr = owner_addr
this is a great idea

2023-01-23 21:56 UTC, TrevorJTClarke commented on contracts/croncat-manager/src/error.rs
> +    #[error("Only up to one ibc coin supported")]
this seems odd - maybe you could help me understand why?

2023-01-23 21:56 UTC, TrevorJTClarke commented on packages/croncat-sdk-manager/src/msg.rs
> -    pub gas_query_fee: Option<Uint64>,
Can you explain why these were removed @Buckram123 ? Do they exist somewhere else? I think we still need this here

2023-01-23 22:03 UTC, Buckram123 commented on contracts/croncat-manager/src/balances.rs
> +            // TODO: check if sender is task_owner
@TrevorJTClarke is it ok to finish it after merge? Can't test it yet)

2023-01-23 22:03 UTC, Buckram123 commented on contracts/croncat-manager/src/balances.rs
> +    // TODO: check if sender is task_owner
@TrevorJTClarke is it ok to finish it after merge? Can't test it yet)

2023-01-23 22:04 UTC, Buckram123 commented on contracts/croncat-manager/src/balances.rs
> +                .ibc_coin
@TrevorJTClarke Yep, so we can have up to 1 ibc, up to 1 cw20 and native coins will be used in any case

2023-01-23 22:07 UTC, Buckram123 commented on packages/croncat-sdk-manager/src/msg.rs
> -    pub gas_query_fee: Option<Uint64>,
> Can you explain why these were removed @Buckram123 ? Do they exist somewhere else? I think we still need this here

My vision here is to make manager keep economics, and gas should be handled by the tasks contract. So after task creation task passes message to the manager with gas to check if enough coins to the task, based of `gas_price`, `agent_fee` and `treasury_fee` configs

2023-01-23 22:46 UTC, Buckram123 commented on contracts/croncat-manager/src/error.rs
> +    #[error("Only up to one ibc coin supported")]
> this seems odd - maybe you could help me understand why?

Didn't we agree on up to 1 ibc and 1 cw20 coin per task?

2023-01-24 18:38 UTC, mikedotexe commented on contracts/croncat-manager/src/balances.rs
> +pub fn query_users_balances(
I think I'd prefer if there were `cw20` somewhere in the method name, but not a massive deal

2023-01-24 18:42 UTC, Buckram123 commented on contracts/croncat-manager/src/balances.rs
> +pub fn query_users_balances(
Agree, thanks

2023-01-24 18:44 UTC, mikedotexe commented on contracts/croncat-manager/src/contract.rs
> +// TODO: It might be not possible to deserialize all of the active agents, need to find better solution
I don't think we're at the point of getting too concerned, we just need a limit

2023-01-24 18:52 UTC, merged