Create mod-generic for generic queries
CronCats/cw-croncat pull request #251
Opened 2023-01-10 10:20 UTC by NinoLipartiia

2023-01-10 17:24 UTC, Buckram123 approved these changes
Nice one

2023-01-10 17:24 UTC, Buckram123 commented on packages/mod-sdk/src/helpers.rs
> +pub fn query_wasm_smart_raw(
Let's move it to the `mod-generic`! I think we decided to keep the logic in the contracts, instead of packages?

2023-01-10 19:51 UTC, NinoLipartiia commented on packages/mod-sdk/src/helpers.rs
> +pub fn query_wasm_smart_raw(
I think we use `query_wasm_smart_raw` in mod-dao too, so I don't want to have it duplicated, what do you think?

2023-01-11 09:12 UTC, NinoLipartiia commented on packages/mod-sdk/src/helpers.rs
> +pub fn query_wasm_smart_raw(
I changed `mod-dao` a bit, so it doesn't use `query_wasm_smart_raw` now. Moving `query_wasm_smart_raw` to `mod-generic`!

2023-01-11 23:52 UTC, TrevorJTClarke requested changes
Super rad stuff - only needs a couple more adjustments to tests!

2023-01-11 23:52 UTC, TrevorJTClarke commented on contracts/mod-generic/src/tests/generic_query.rs
> +    let generic_query = GenericQuery {
Would love to see a comment here about how this is checking the weight of the second member is greater than 1.

2023-01-11 23:52 UTC, TrevorJTClarke commented on contracts/mod-generic/src/tests/generic_query.rs
> +    assert!(res.result);
Can we add a fail case too?

2023-01-11 23:52 UTC, TrevorJTClarke commented on contracts/mod-generic/src/tests/generic_query.rs
> +    assert!(res.result);
Can we check the res.data as well?

2023-01-11 23:52 UTC, TrevorJTClarke commented on contracts/mod-generic/src/tests/generic_query.rs
> +        ordering: ValueOrdering::UnitAbove,
Can we change to UnitBelow? Since we have UnitAbove in the tests above

2023-01-12 20:29 UTC, merged