Croncat factory
CronCats/cw-croncat pull request #259
Opened 2023-01-13 16:41 UTC by Buckram123

Implementation based of https://github.com/CronCats/cw-croncat/wiki/%F0%9F%8F%AD-Factory-Architecture

2023-01-13 19:46 UTC, TrevorJTClarke commented on contracts/croncat-factory/src/contract.rs
> +    let mut versions = Vec::with_capacity(metadatas.len());
Would this ever require pagination? Kinda think no, but want to make sure theres no query gas limitations

2023-01-13 19:46 UTC, TrevorJTClarke commented on contracts/croncat-factory/src/contract.rs
> +pub fn query_latest_contracts(deps: Deps) -> StdResult<Vec<EntryResponse>> {
cant wait for this!!!

2023-01-13 19:49 UTC, TrevorJTClarke commented on packages/croncat-sdk-factory/Cargo.toml
> +authors = []
feel free to add yourself

2023-01-13 19:50 UTC, TrevorJTClarke commented on packages/croncat-sdk-factory/src/msg.rs
> +    pub manager_module_instantiate_info: ModuleInstantiateInfo,
still have reservations about this living here - i believe it should be specified during deploy only

2023-01-13 19:51 UTC, TrevorJTClarke commented on packages/croncat-sdk-factory/src/msg.rs
> +    pub schema: String,
Make this optional please :)

2023-01-13 19:52 UTC, TrevorJTClarke commented on packages/croncat-sdk-factory/src/msg.rs
> +    pub label: String,
did you mean to change this to `contract_name`?

2023-01-13 19:52 UTC, TrevorJTClarke commented on packages/croncat-sdk-factory/src/msg.rs
> +pub struct ContractMetadata {
This is the same (basically) as `ModuleInstantiateInfo ` - the new ModuleInstantiateInfo has what we discussed on the call. Can you migrate to that for all instead?

2023-01-13 19:57 UTC, TrevorJTClarke commented
> * migrate with a little demo

Will definitely need a README on this contract :)

2023-01-13 20:29 UTC, Buckram123 commented on contracts/croncat-factory/src/contract.rs
> +    let latest_version = LATEST_VERSIONS
> Are you thinking this would be a future update?

Yep, thanks for noticing, i'd better add comment here.
Still not sure about the flow of checking that, obvious for manager contract, but what for others?

2023-01-13 20:31 UTC, Buckram123 commented on contracts/croncat-factory/src/contract.rs
> +    let mut entries = Vec::with_capacity(metadatas.len());
Was thinking about it too! Depends on how much versions we plan to maintain.
I guess it could grow fast for library contracts

2023-01-13 20:39 UTC, Buckram123 commented on contracts/croncat-factory/src/state.rs
> +pub const LATEST_ADDRS: Map<&str, Addr> = Map::new("latest_addrs");
> Only question here is - is this more efficient than doing indexed map?

Most of the time spent here deciding the state :D Had so many options during it. And it comes to the preferences, really. 
Two things pushed me away from the indexed map: 
- Didn't want to store unchecked address in the state
- Want to be able to [safely rawquery](https://docs.rs/cw-storage-plus/latest/cw_storage_plus/struct.Map.html#method.query) it

2023-01-13 20:45 UTC, Buckram123 commented on packages/croncat-sdk-factory/src/msg.rs
> +    pub label: String,
> did you mean to change this to `contract_name`?

Like that name too! Not sure, how to not make it confusing. We can have both, one for chain(label) and other for the state(contract_name)

2023-01-13 21:11 UTC, Buckram123 commented on contracts/croncat-factory/src/contract.rs
> +pub fn instantiate(
>What are the implications of this vs, new factory adopting old versions of previously deployed contracts? 

So you think just taking addresses of already deployed contracts in instantiate message will be fine? I guess having it 1 tx should be faster for re-deployments. Also it makes sure none of our instantiates of core contracts fails and we have factory that contains manager, agents, but not the tasks! Thoughts?

> Im inclined to simplify this instantiate so we cut down on complexity. I'm 100% okay with multiple TXNs for each new contract.

It sounds a little more complex to me if we take addr and it's more error prone instead of a freshly instantiated contract. I'm up for something like
```rust
pub struct InstantiateMsg{
 pub owner_addr: String,
 pub manager_module_instantiate_info: ModuleInfo,
 pub tasks_module_instantiate_info: ModuleInfo,
 pub agents_module_instantiate_info: ModuleInfo,
}

pub enum ModuleInfo{
 /// Needs to be instantiated
 ModuleInstantiateInfo {
 ...
 },
 /// Already instantiated contract
 ModuleAddr {
 contract_addr: String
 },
}
```
To cover both cases!

> Thoughts? If you agree, lets simplify instantiate down to only the base factory needs.

What's a minimal requirments for a factory needed? Can we roll with zero croncat contracts in the state?

2023-01-13 21:11 UTC, Buckram123 commented on contracts/croncat-factory/src/contract.rs
> +        ExecuteMsg::UpdateMetadataChangelog {
> What do you think about moving into just `UpdateMetadata`, and for now only updates changelog, so future integrations (if any) can remain simpler

I like that!

2023-01-13 21:12 UTC, Buckram123 commented on contracts/croncat-factory/src/contract.rs
> +        .add_attribute("action", "deploy")
> Thinking it would be nice to add attributes for version kind & contract_name

Thanks

2023-01-13 21:13 UTC, Buckram123 commented on contracts/croncat-factory/src/contract.rs
> +    let mut entries = Vec::with_capacity(metadatas.len());
So I'll just add it, so we don't redeploy it, we are not losing anything anyway :)

2023-01-13 21:16 UTC, Buckram123 commented on contracts/croncat-factory/src/contract.rs
> +    let mut versions = Vec::with_capacity(metadatas.len());
> Would this ever require pagination? Kinda think no, but want to make sure theres no query gas limitations

Unless croncat dao decides to break it - I don't think so. What's your thoughts on `Order`? Should we give latest versions first?

2023-01-13 21:21 UTC, Buckram123 commented on packages/croncat-sdk-factory/src/msg.rs
> +pub struct ContractMetadata {
Right, only difference is `VersionKind`. I'm fine to specify it if we decide to deploy contracts one by one.
Small note if we decide to not instantiate all core contracts in a single tx: make paused default to the `true`

2023-01-16 23:51 UTC, TrevorJTClarke commented on contracts/croncat-factory/src/contract.rs
> +pub fn instantiate(
Sorry, i think i miscommunicated a little.

The idea is that there is no logic for any of the modules/contracts in the factory instantiate. Only `pub owner_addr: String` basically

2023-01-16 23:53 UTC, TrevorJTClarke commented on contracts/croncat-factory/src/contract.rs
> +    let latest_version = LATEST_VERSIONS
I think it applies to any stateful contracts, since they will likely have a `paused` boolean in its state.

2023-01-16 23:53 UTC, TrevorJTClarke commented on contracts/croncat-factory/src/contract.rs
> +    let mut entries = Vec::with_capacity(metadatas.len());
okay thanks!

2023-01-16 23:53 UTC, TrevorJTClarke commented on contracts/croncat-factory/src/contract.rs
> +    let mut versions = Vec::with_capacity(metadatas.len());
ohhh good thought. Yeah definitely

2023-01-16 23:54 UTC, TrevorJTClarke commented on contracts/croncat-factory/src/state.rs
> +pub const LATEST_ADDRS: Map<&str, Addr> = Map::new("latest_addrs");
thats right, yes i want rawquery to be priority on this!

2023-01-16 23:55 UTC, TrevorJTClarke commented on packages/croncat-sdk-factory/src/msg.rs
> +    pub label: String,
I dont get the difference tho? Let's unify to 1 only, i think `contract_name` fits all cases

2023-01-16 23:56 UTC, TrevorJTClarke commented on packages/croncat-sdk-factory/src/msg.rs
> +pub struct ContractMetadata {
Thats fair. I would like to go non-instantiate route, all deploys use individual methods, outside of factory instantiate to keep this contract super generic. That way this can be migrated to simpler as well

2023-01-18 18:23 UTC, TrevorJTClarke requested changes
This is great @Buckram123!! Couple minor owner checks needed

2023-01-18 18:23 UTC, TrevorJTClarke commented on contracts/croncat-factory/Cargo.toml
> +authors = ["buckram <buckram123@gmail.com>"]
k, another dumb idea = `{ workspace = true }` could work here? 
Im fine with individual here too

2023-01-18 18:23 UTC, TrevorJTClarke commented on contracts/croncat-factory/src/contract.rs
> -const CRONCAT_AGENTS_REPLY_ID: u64 = 2;
TY!

2023-01-18 18:23 UTC, TrevorJTClarke commented on contracts/croncat-factory/src/contract.rs
> +/// Note: this will override contract metadata if same contract name and version was stored already
GTK, thanks!

2023-01-18 18:23 UTC, TrevorJTClarke commented on contracts/croncat-factory/src/contract.rs
> +        .add_attribute("sender", info.sender))
Appreciate this removal!
For sender here, i believe its already part of the logs, so having that here is duplication

2023-01-18 18:23 UTC, TrevorJTClarke commented on contracts/croncat-factory/src/contract.rs
> +fn execute_update_config(deps: DepsMut, owner_addr: String) -> Result<Response, ContractError> {
if we're updating owner, we need to validate previous owner is the sender for safety

2023-01-18 18:23 UTC, TrevorJTClarke commented on contracts/croncat-factory/src/contract.rs
> +    let metadata =
Need to check if owner is sender

2023-01-18 18:23 UTC, TrevorJTClarke commented on contracts/croncat-factory/src/contract.rs
> +                        metadata.schema = schema;
noice!

2023-01-18 18:32 UTC, Buckram123 commented on contracts/croncat-factory/src/contract.rs
> +fn execute_update_config(deps: DepsMut, owner_addr: String) -> Result<Response, ContractError> {
@TrevorJTClarke 
https://github.com/CronCats/cw-croncat/blob/b81b432ab363ef6752534d78a74c9ff482434723/contracts/croncat-factory/src/contract.rs#L84
It's checked for every execute action inside `factory`!

2023-01-18 18:33 UTC, Buckram123 commented on packages/croncat-sdk-factory/src/msg.rs
>  // TODO: migrate
@TrevorJTClarke What do you mean by that

2023-01-18 18:34 UTC, TrevorJTClarke commented on packages/croncat-sdk-factory/src/msg.rs
>  // TODO: migrate
The migration logic :)

2023-01-18 18:35 UTC, TrevorJTClarke commented on contracts/croncat-factory/src/contract.rs
> +fn execute_update_config(deps: DepsMut, owner_addr: String) -> Result<Response, ContractError> {
oh yeah - thats right - sorry about that :)

2023-01-18 18:38 UTC, TrevorJTClarke approved these changes

2023-01-19 12:17 UTC, Buckram123 commented on packages/croncat-sdk-factory/src/msg.rs
>  // TODO: migrate
I was looking at fields instead of `TODO` :duck:

2023-01-19 12:19 UTC, merged