[FIX] 2 active agents, 1 agent did the tasks for other agent
CronCats/cw-croncat pull request #268
Opened 2023-01-17 22:49 UTC by deveusss

Closes #246

2023-01-17 23:57 UTC, TrevorJTClarke requested changes
Thanks @deveusss - left comments inline!

2023-01-17 23:57 UTC, TrevorJTClarke commented on contracts/cw-croncat/src/balancer.rs
> +
can remove?

2023-01-17 23:57 UTC, TrevorJTClarke commented on contracts/cw-croncat/src/balancer.rs
> +                    diff.dedup();
This dedup - is not required because rich_indices was dedup above, right? can remove?

2023-01-17 23:57 UTC, TrevorJTClarke commented on contracts/cw-croncat/src/balancer.rs
>                      rich_agents.sort_by(|a, b| a.2.cmp(&b.2));
not a fan of `rich_agents`, let's change to better naming: `current_agents`

2023-01-17 23:57 UTC, TrevorJTClarke commented on contracts/cw-croncat/src/balancer.rs
> -        RoundRobinBalancer::new(BalancerMode::ActivationOrder)
I think @deveusss we should actually remove all logic for ActivationOrder if we're not using. Leaving unused code is not good in blockchain contexts.

2023-01-17 23:57 UTC, TrevorJTClarke commented on contracts/cw-croncat/src/tests/balancer.rs
> +        (Some(3), Some(3)),
Would like to see a couple more cases added for extra assurance:
* `(Some(1), Some(1))`
* `(Some(3), Some(0))`
* `(Some(0), Some(3))`
* `(Some(4), Some(6))`
* `(Some(0), Some(0))`
* `(Some(23), Some(37))`
* `(Some(345), Some(897))`

2023-01-17 23:57 UTC, TrevorJTClarke commented on contracts/cw-croncat/src/tests/balancer.rs
> +    let mut local_test = |slots: (Option<u64>, Option<u64>),
This is a pretty big fn, consider breaking out for clarity or adding comments throughout or best case BOTH ;)

2023-01-18 19:27 UTC, TrevorJTClarke commented on contracts/cw-croncat/src/tests/balancer.rs
> +    let mut result = Vec::<(&str, u64, u64)>::new();
hey @deveusss just to make sure im following - when agent u64 is `1` they are "currently active" which means they will skip getting work until they become `0` again?

2023-01-18 19:31 UTC, TrevorJTClarke commented on contracts/cw-croncat/src/tests/balancer.rs
> +    }
Awesome, thanks for covering the additional cases @deveusss!!

I didn't see any tests that span multiple blocks, do you have this already?
If not, i want to make 100% sure the distribution block after block is ordering properly.

So example: (given default config of tasks per agent 3)
* Block 123 - agent 1 is active and gets 3 tasks. Agent 2 is inactive
* Block 124 - agent 2 is active and gets 3 task. Agent 1 is inactive
* Block 125 - agent 1 is active and gets 3 task2. Agent 2 is inactive

And i want to have this test 2 agents setup and  5 agents setup.

NOTE: inactive does not mean pending.

2023-01-18 19:51 UTC, deveusss commented on contracts/cw-croncat/src/tests/balancer.rs
> +    let mut result = Vec::<(&str, u64, u64)>::new();
agent_active_indices keeps count of task when agents gets extra, then we will use this values for valid order.

Agent1 - 2 tasks,
Agent2 - 1 task
Agent3 - 0 task
Then using agent_active_indices we will order agents 
Agent3
Agent2
Agent1

2023-01-18 20:04 UTC, TrevorJTClarke commented on contracts/cw-croncat/src/tests/balancer.rs
> +    let mut result = Vec::<(&str, u64, u64)>::new();
> Then using agent_active_indices we will order agents
> Agent3
> Agent2
> Agent1

wait, wouldn't it be:
Agent3
Agent1
Agent2

2023-01-18 20:12 UTC, deveusss commented on contracts/cw-croncat/src/tests/balancer.rs
> +    let mut result = Vec::<(&str, u64, u64)>::new();
will add more tests with blocks

2023-01-21 02:34 UTC, deveusss commented on contracts/cw-croncat/src/tests/balancer.rs
> +    }
but what if on block Block 125  we have more then 3 tasks, for example 5?

2023-03-23 21:22 UTC, closed without merging