[FEATURE] Agent split
CronCats/cw-croncat pull request #270
Opened 2023-01-19 20:27 UTC by deveusss

2023-01-19 23:56 UTC, deveusss commented
to be done:
[] Tests
[] Comments
[] Typescript stuff

2023-01-20 19:29 UTC, Buckram123 commented on contracts/croncat-agents/src/contract.rs
> +use croncat_sdk_core::types::Config;
```suggestion
use croncat_sdk_agents::types::Config;
```
Agents should have it's own config!

2023-01-20 19:29 UTC, Buckram123 commented on contracts/croncat-agents/src/contract.rs
> +    let config: Config = CONFIG.load(deps.storage)?;
Where does it load CONFIG from? :rofl:

2023-01-20 19:31 UTC, Buckram123 commented on packages/croncat-sdk-agents/src/msg.rs
> +    WithdrawReward {},
```suggestion
    WithdrawReward {},
    NewTaskCreated {},
```
Can you implement please this logic: 
https://github.com/CronCats/cw-croncat/blob/b920d1a5d5b1730397b04acdbba205eacfd487bd/contracts/cw-croncat/src/tasks.rs#L380-L395

2023-01-20 19:33 UTC, Buckram123 commented on packages/croncat-sdk-agents/src/msg.rs
> +pub enum AgentQueryMsg {
```suggestion
#[cw_serde]
#[derive(QueryResponses)]
pub enum AgentQueryMsg {
```
Let's use `QueryResponse` for easier schema handle!

2023-01-20 19:33 UTC, Buckram123 commented on packages/croncat-sdk-agents/src/msg.rs
> +    pub balance: Uint128,
Do we want to return `rewards_balance` here or only from manager contract? @TrevorJTClarke

2023-01-20 19:35 UTC, Buckram123 commented on packages/croncat-sdk-agents/src/msg.rs
> +}
Should think of better response for querying with offset!

2023-01-20 19:37 UTC, Buckram123 commented on packages/croncat-sdk-core/Cargo.toml
> +cw20 = { workspace = true }
I don't think `packages/croncat-sdk-core/*` should be used for agents yet, lets revert changes here!

2023-01-20 19:37 UTC, Buckram123 commented on packages/croncat-sdk-tasks/Cargo.toml
> +croncat-sdk-core = { workspace = true }
revert it too!

2023-01-20 19:39 UTC, Buckram123 commented on packages/croncat-sdk-tasks/src/types.rs
> +}
Is it needed for agents contract?

2023-01-20 19:40 UTC, Buckram123 commented on contracts/croncat-agents/src/contract.rs
> +        ExecuteMsg::WithdrawReward {} => withdraw_agent_balance(deps, &info.sender),
```suggestion
```
This method should be only on manager contract, I believe!

2023-01-20 19:40 UTC, Buckram123 commented on contracts/croncat-agents/src/contract.rs
> +        })?;
I would like to have typed errors, so it's easier to test and debug!

2023-01-20 19:41 UTC, Buckram123 commented on contracts/croncat-agents/src/contract.rs
> +
can we get pagination here?

2023-01-20 19:42 UTC, Buckram123 commented on contracts/croncat-agents/src/contract.rs
> +            msg: "Agent is not active!".to_owned(),
let's add typed errors!

2023-01-20 19:45 UTC, Buckram123 commented on contracts/croncat-agents/src/contract.rs
> +    }
What do you mean by `InsufficientFunds` :smile:
It should return "Doesn't accept deposit" or something like that

2023-01-20 19:46 UTC, Buckram123 commented on contracts/croncat-agents/src/contract.rs
> +    }
Do we need this logic at all? And what's our flow for that @TrevorJTClarke?

2023-01-20 19:47 UTC, Buckram123 commented on contracts/croncat-agents/src/contract.rs
> +}
It shouldn't send coins ever

2023-01-20 20:04 UTC, deveusss commented on contracts/croncat-agents/src/contract.rs
> +use croncat_sdk_core::types::Config;
yes, but from this config I get native_denom

2023-01-20 20:06 UTC, deveusss commented on contracts/croncat-agents/src/contract.rs
> +}
what do u mean, more details please @Buckram123

2023-01-20 20:07 UTC, Buckram123 commented on contracts/croncat-agents/src/contract.rs
> +use croncat_sdk_core::types::Config;
> yes, but from this config I get native_denom

Why do you need native_denom?

2023-01-20 20:08 UTC, Buckram123 commented on contracts/croncat-agents/src/contract.rs
> +}
> what do u mean, more details please @Buckram123

Coins should not leave manager!

2023-01-20 21:27 UTC, deveusss commented on contracts/croncat-agents/src/contract.rs
> +}
but coins here is just agent balance going to reward address, are we moving rewards part into manager?

2023-01-20 22:07 UTC, mikedotexe commented on contracts/croncat-agents/src/contract.rs
> +    let config: Config = CONFIG.load(deps.storage)?;
Yeah I think this is giving me an error

2023-01-20 23:52 UTC, deveusss commented on contracts/croncat-agents/src/contract.rs
> +use croncat_sdk_core::types::Config;
for sending rewards

2023-01-21 02:20 UTC, deveusss commented on packages/croncat-sdk-tasks/Cargo.toml
> +croncat-sdk-core = { workspace = true }
we have helper stuff in croncat-sdk-core

2023-01-21 02:20 UTC, deveusss commented on packages/croncat-sdk-agents/src/msg.rs
> +}
yeah refactoring is needed for the whole project))

2023-01-21 02:21 UTC, deveusss commented on packages/croncat-sdk-core/Cargo.toml
> +cw20 = { workspace = true }
why? croncat-sdk-core can contain helper methods

2023-01-21 02:21 UTC, deveusss commented on packages/croncat-sdk-tasks/src/types.rs
> +}
yes in balancer

2023-01-21 02:58 UTC, mikedotexe requested changes

2023-01-21 02:58 UTC, mikedotexe commented on contracts/croncat-agents/src/contract.rs
> +        ExecuteMsg::CheckInAgent {} => accept_nomination_agent(deps, info, env),
I noticed that in commit fd670e9520130a068c42f995b6e3d6324c972b9b, the `WithdrawReward` variant was removed? I think that's causing `just optimize` to fail with:

```
error[E0004]: non-exhaustive patterns: `ExecuteMsg::WithdrawReward {  }` not covered
```

I reverted that commit (locally) and it's building now. Think we're going to need that back

2023-01-21 09:35 UTC, Buckram123 commented on packages/croncat-sdk-core/Cargo.toml
> +cw20 = { workspace = true }
Isn't `croncat-sdk-core` for `croncat-manager` contract? Is there any helpers that will get used in every contract?

2023-01-22 01:11 UTC, deveusss commented on packages/croncat-sdk-core/Cargo.toml
> +cw20 = { workspace = true }
why not croncat-sdk-manager for croncat-manager? we should be consistent here!

2023-01-22 01:15 UTC, deveusss commented on contracts/croncat-agents/src/contract.rs
> +        })?;
Multiple errors could be caught here, we don't know the exact error

2023-01-22 01:20 UTC, deveusss commented on contracts/croncat-agents/src/contract.rs
> +        ExecuteMsg::WithdrawReward {} => withdraw_agent_balance(deps, &info.sender),
When agent is removed, we are calling withdraw rewards, how to deal with that if we are removing WithdrawReward? @Buckram123

2023-01-22 09:45 UTC, Buckram123 commented on contracts/croncat-agents/src/contract.rs
> +        ExecuteMsg::WithdrawReward {} => withdraw_agent_balance(deps, &info.sender),
@deveusss should get called "remove_manager" on manager contract too!

2023-01-23 10:37 UTC, deveusss commented on contracts/croncat-agents/src/contract.rs
> +            msg: "Agent is not active!".to_owned(),
√

2023-01-23 10:41 UTC, deveusss commented on packages/croncat-sdk-agents/src/msg.rs
> +    WithdrawReward {},
√

2023-01-23 10:43 UTC, deveusss commented on contracts/croncat-agents/src/contract.rs
> +    }
√

2023-01-23 20:27 UTC, mikedotexe requested changes
When I run `just optimize` I am getting this error:

```
error[E0433]: failed to resolve: could not find `macos` in `os`
 --> contracts/croncat-agents/src/balancer.rs:1:14
  |
1 | use std::os::macos::raw::stat;
  |              ^^^^^ could not find `macos` in `os`
```

2023-01-23 21:17 UTC, Buckram123 commented on contracts/croncat-agents/src/contract.rs
> +        })?;
```suggestion
?
```
Do we need to wrap it into generic then? @deveusss

2023-01-25 22:58 UTC, mikedotexe commented on contracts/croncat-agents/src/contract.rs
> +    }
I think so, as discussed in Discord. it's working now after recent commits. good eye tho

2023-01-25 22:59 UTC, merged