[FEATURE] Withdraw rewards functionality for agent and manager contracts
CronCats/cw-croncat pull request #288
Opened 2023-01-29 11:19 UTC by deveusss

See more in #287

2023-01-30 18:40 UTC, TrevorJTClarke requested changes
@deveusss see comments below - this needs logic moved.
Manager is the only contract for balance handling, agent cannot have any logic handling balances.

2023-01-30 18:40 UTC, TrevorJTClarke commented on contracts/croncat-agents/src/contract.rs
> +use cosmwasm_std::QuerierWrapper;
@deveusss these deps should all be in the below list

2023-01-30 18:40 UTC, TrevorJTClarke commented on contracts/croncat-agents/src/contract.rs
> +        ExecuteMsg::WithdrawRewards {} => execute_withdraw_rewards(deps, info),
@deveusss this implementation needs to live within the manager contract with the other balances functionality

2023-01-30 18:40 UTC, TrevorJTClarke commented on contracts/croncat-agents/src/contract.rs
> +pub fn execute_withdraw_rewards(
move to manager

2023-01-30 18:40 UTC, TrevorJTClarke commented on contracts/croncat-agents/src/contract.rs
> +pub(crate) fn withdraw_rewards(
move to manager

2023-01-30 18:40 UTC, TrevorJTClarke commented on contracts/croncat-agents/src/external.rs
> +    pub fn create_withdraw_rewards_submsg(
not needed, when moved to manager

2023-01-30 18:40 UTC, TrevorJTClarke commented on contracts/croncat-manager/src/contract.rs
> +    let rewards = TREASURY_BALANCE.load(deps.storage)?;
@deveusss this is actually wrong.
The manager has 2 buckets of balances (which is why this logic needs to move) where we have 1 for agents, 1 for treasury (which only pays the DAO). This logic actually crosses the boundary of 2 diff reward pools

2023-01-30 18:52 UTC, TrevorJTClarke commented on contracts/croncat-manager/src/contract.rs
> +    let rewards = TREASURY_BALANCE.load(deps.storage)?;
See here: https://github.com/CronCats/cw-croncat/blob/beta/split-0.0.0-withdraw-rewards/contracts/croncat-manager/src/state.rs#L13

2023-01-30 18:55 UTC, deveusss commented on contracts/croncat-agents/src/contract.rs
> +        ExecuteMsg::WithdrawRewards {} => execute_withdraw_rewards(deps, info),
√

2023-01-30 18:55 UTC, deveusss commented on contracts/croncat-agents/src/contract.rs
> +pub fn execute_withdraw_rewards(
√

2023-01-30 19:18 UTC, deveusss commented on contracts/croncat-agents/src/external.rs
> +    pub fn create_withdraw_rewards_submsg(
this one need for agent unregister

2023-01-31 07:30 UTC, TrevorJTClarke commented on contracts/croncat-manager/src/contract.rs
> +    let agent_rewards = AGENT_REWARDS
awesome, thank you!

2023-01-31 07:32 UTC, TrevorJTClarke approved these changes

2023-01-31 13:48 UTC, merged