[FEATURE] Proxy call implementation
CronCats/cw-croncat pull request #289
Opened 2023-01-30 22:18 UTC by Buckram123

WIP:

[ ] - tests

Changes, from original implementation:

1. `reply_queue` and `reply_index` was replaced with a single 
```
REPLY_QUEUE: Item<QueueItem>
 ```
2. QueueItem got simplyfied from https://github.com/CronCats/cw-croncat/blob/b920d1a5d5b1730397b04acdbba205eacfd487bd/contracts/cw-croncat/src/state.rs#L62-L76
to:
```rust
pub struct QueueItem {
    pub task: croncat_sdk_tasks::types::TaskResponse,
    pub agent_addr: Addr,
    /// Storing any errors that happened to return
    pub failures: Vec<(u8, String)>,
}
```
3. Submessages of the task's actions only `reply_on_error`, except for the last submessage, where we finalize task

Reasoning for 1 and 2:
- We don't need to keep such complex state if cosmwasm protects us from reentrancy attacks by design
  - source: https://docs.cosmwasm.com/docs/architecture/smart-contracts/#avoiding-reentrancy-attacks
Reasoning for 3:
- Cosmwasm keeps ordering of the submessages and we don't need to do anything with successful events, unless it's a last action
  - sources: https://docs.rs/cosmwasm-std/latest/cosmwasm_std/struct.Response.html#structfield.messages and https://github.com/CosmWasm/cosmwasm/blob/main/SEMANTICS.md#order-and-rollback

2023-01-31 07:43 UTC, TrevorJTClarke commented on contracts/croncat-manager/src/contract.rs
> +            &croncat_sdk_tasks::msg::TasksQueryMsg::TaskWithTransforms { task_hash },
@Buckram123 why `TaskWithTransforms` here?

2023-01-31 07:43 UTC, TrevorJTClarke commented on contracts/croncat-manager/src/contract.rs
> +        // TODO: help to find a better attributes for this
seems enough for me. less is more :)

2023-01-31 07:43 UTC, TrevorJTClarke commented on contracts/croncat-manager/src/contract.rs
> +                let failures: Vec<Attribute> = queue_item
Does this mean we'll be able to debug submsgs!?

2023-01-31 12:01 UTC, Buckram123 commented on contracts/croncat-manager/src/contract.rs
> +            &croncat_sdk_tasks::msg::TasksQueryMsg::TaskWithTransforms { task_hash },
It queries task with queries, and if it has transforms it applies them.
What do you think, should transforms happen on the tasks or manager contract?

2023-01-31 12:02 UTC, Buckram123 commented on contracts/croncat-manager/src/contract.rs
> +                let failures: Vec<Attribute> = queue_item
Yeah, so anyone can check his executed task and see what actions failed!)

2023-01-31 22:31 UTC, TrevorJTClarke commented on contracts/croncat-manager/src/contract.rs
> +            &croncat_sdk_tasks::msg::TasksQueryMsg::TaskWithTransforms { task_hash },
are you saying that it does queries & transforms within the tasks contract?
I figured all proxy_call logic including queries / transforms would live within manager. This way its consistent behaviour across tasks (in the event we support multiple task contracts 😯)

2023-01-31 22:32 UTC, TrevorJTClarke commented on contracts/croncat-manager/src/contract.rs
> +                let failures: Vec<Attribute> = queue_item
This is life saving then!!!!!!!!

2023-01-31 22:40 UTC, Buckram123 commented on contracts/croncat-manager/src/contract.rs
> +            &croncat_sdk_tasks::msg::TasksQueryMsg::TaskWithTransforms { task_hash },
Okay then, gonna move it back to the manager then 🧨

2023-02-01 05:22 UTC, TrevorJTClarke commented on contracts/croncat-manager/src/contract.rs
> +    let invalidated_after_transform = if let Ok(amounts) =
thats pretty neat!

2023-02-01 05:24 UTC, TrevorJTClarke commented on contracts/croncat-manager/src/contract.rs
> +        if !query_res.result {
Still thinking this piece through. I was hoping we support a `match` so we can do just regular query or CronCat flavored `QueryResponse` which does the check for result here.
This allows any task to have a query + transform for both schedule or event driven. Where only event driven ones have `QueryResponse` result check.

HMU in discord if you wanna clarify!

2023-02-01 05:27 UTC, TrevorJTClarke requested changes
Looking like solid progress!!
Left a couple notes in there @Buckram123 :)

2023-02-01 07:25 UTC, Buckram123 commented on contracts/croncat-manager/src/contract.rs
> +        if !query_res.result {
@TrevorJTClarke so adding `check_result` toggle to the CronCatQuery is enough right?

2023-02-01 07:26 UTC, TrevorJTClarke commented on contracts/croncat-manager/src/contract.rs
> +        if !query_res.result {
@Buckram123 yeah - thats a good plan

2023-02-01 18:44 UTC, Buckram123 commented on packages/croncat-sdk-tasks/src/types.rs
> +    /// This is done primarily to save up gas from executing another contract during `proxy_call`
> Cw20 during create_task - how does this work? When i pass in task.cw20, is it a reference to a pre-deposited balance or is it part of a receiver chain?

Hey @TrevorJTClarke Is it good enough description about lifetime of the cw20's inside a task?

2023-02-01 18:55 UTC, TrevorJTClarke commented on packages/croncat-sdk-tasks/src/types.rs
> +    /// This is done primarily to save up gas from executing another contract during `proxy_call`
thats perfect, thanks!

2023-02-01 18:56 UTC, TrevorJTClarke commented on contracts/croncat-manager/src/contract.rs
> +        if query.check_result && !query_res.result {
This feels much better. I can't think of how to do better :P

2023-02-01 18:57 UTC, TrevorJTClarke commented on contracts/croncat-manager/src/contract.rs
> +    // because it could have been changed through transform
This is great - actually had a note from Pupmos months ago on this exact problem happening from not checking

2023-02-01 19:05 UTC, TrevorJTClarke requested changes
@Buckram123 tiny tiny thangs

2023-02-01 19:14 UTC, Buckram123 commented on contracts/croncat-manager/src/tests/contracts.rs
> +#![allow(unused)]
Left it on purpose, have few not used (anymore) contracts for testing. If we find some strange behavior or think about some task-flow that needs to be covered would be nice to get it ready for fast-checking it

2023-02-01 19:16 UTC, Buckram123 commented on contracts/croncat-manager/src/tests/helpers.rs
> +#[allow(unused)]
Maybe used later. It is in the tests, should be fine to keep it unused)

2023-02-01 19:22 UTC, Buckram123 commented on packages/croncat-sdk-tasks/src/types.rs
> +    pub check_result: bool,
So change to the `contract_addr` and add comment to what type of addr it is, right?

2023-02-01 19:25 UTC, TrevorJTClarke commented on packages/croncat-sdk-tasks/src/types.rs
> +    pub check_result: bool,
yes please!

2023-02-01 19:26 UTC, TrevorJTClarke commented on packages/croncat-sdk-tasks/src/types.rs
> +    pub check_result: bool,
`QueryResponse` is still the response tho, not the request. so it shouldnt change

2023-02-01 19:37 UTC, Buckram123 commented on contracts/croncat-manager/src/contract.rs
> +    // because it could have been changed through transform
Lol :D

2023-02-01 19:37 UTC, TrevorJTClarke approved these changes

2023-02-01 19:49 UTC, merged