Beta/split 0.0.0 fixes
CronCats/cw-croncat pull request #294
Opened 2023-01-31 17:26 UTC by deveusss

- [x] In query_users_balances change "wallet" to "address" to remove confusion
- [x] In instantiate TREASURY_BALANCE starts as zero, but info could have funds - so maybe add funds into TREASURY_BALANCE or just error if info funds attached
[x] Can not pass funds in factory deploy

2023-01-31 19:35 UTC, Buckram123 requested changes
I personally against attached deposit being the standard way to initialize treasury balance, it doesn't make sense if croncat-factory owner is a croncat-dao itself, why would they ping-pong balance in and out?

Can't think it can be useful for anything, so I'm more towards blocking attached funds on initialize, at least for now! What's your thoughts on that? @TrevorJTClarke  @mikedotexe @NinoLipartiia @deveusss

2023-01-31 19:35 UTC, Buckram123 commented on contracts/croncat-manager/src/contract.rs
> +        .ok_or(ContractError::NoTreasuryFundsAttached {})?;
Let's say we have this situation: 
- [20coinA, 30coinB] attached and `config.denom` is `coinA`

Should we fail tx if other coins were attached or what to do with coinB? @TrevorJTClarke

2023-01-31 19:35 UTC, Buckram123 commented on contracts/croncat-manager/src/contract.rs
> +        .ok_or(ContractError::NoTreasuryFundsAttached {})?;
```suggestion
```
It should allow empty deposit!

2023-01-31 19:35 UTC, Buckram123 commented on contracts/croncat-manager/src/tests/contract_tests.rs
> +    let manager_addr = init_manager(&mut app, instantiate_msg, send_funds).unwrap();
Let's not have it standard way to initialize contract

2023-01-31 19:44 UTC, deveusss commented on contracts/croncat-manager/src/contract.rs
> +        .ok_or(ContractError::NoTreasuryFundsAttached {})?;
Trevors comment "TREASURY_BALANCE or just error if no funds attached"

2023-01-31 19:45 UTC, deveusss commented on contracts/croncat-manager/src/tests/contract_tests.rs
> +    let manager_addr = init_manager(&mut app, instantiate_msg, send_funds).unwrap();
Copy it from agent tests

2023-01-31 19:46 UTC, deveusss commented on contracts/croncat-manager/src/contract.rs
> +        .ok_or(ContractError::NoTreasuryFundsAttached {})?;
For now its not failing if others are attached by if no funds with default denom - it will fail

2023-01-31 19:50 UTC, Buckram123 commented on contracts/croncat-manager/src/contract.rs
> +        .ok_or(ContractError::NoTreasuryFundsAttached {})?;
"or just error if info funds attached"
pretty sure it means
```rust
if info.funds.is_empty{
    return Err();
}
```

2023-01-31 19:50 UTC, Buckram123 commented on contracts/croncat-manager/src/tests/contract_tests.rs
> +    let manager_addr = init_manager(&mut app, instantiate_msg, send_funds).unwrap();
I mean about positive balance at treasury from the start)

2023-01-31 20:11 UTC, deveusss commented on contracts/croncat-manager/src/contract.rs
> +        .ok_or(ContractError::NoTreasuryFundsAttached {})?;
ahh, true

2023-01-31 20:19 UTC, deveusss commented on contracts/croncat-manager/src/contract.rs
> +        .ok_or(ContractError::NoTreasuryFundsAttached {})?;
updated it, so now funds are added into treasure balance

2023-01-31 22:29 UTC, TrevorJTClarke approved these changes
@deveusss lookin good! couple minor things.

RE: Things @Buckram123 brought up - theres some back in forth in my head about funds for future needs, i would rather support this way to start and remove if need be.

2023-01-31 22:29 UTC, TrevorJTClarke commented on contracts/croncat-manager/src/balances.rs
> +    if info.funds.len() > 3 {
@deveusss @Buckram123 whats the hardcoded value here for? Is there a reason its not higher like 10 or just simply 1?

2023-01-31 22:29 UTC, TrevorJTClarke commented on justfile
> +	yarn go
@deveusss whats the core use-case here? Will CI/CD be running this? If so, can we guarantee other things like build & optimize run first?

2023-01-31 22:29 UTC, TrevorJTClarke commented on scripts/deployment/src/manager.ts
> +		const funds:Coin[]=[coin(50,denom)];
@deveusss likely need some `cargo fmt --` love here

2023-01-31 22:37 UTC, Buckram123 commented on contracts/croncat-manager/src/balances.rs
> +    if info.funds.len() > 3 {
Didn't we decide to keep up to 1 `config.denom` and 1 non-`config.denom`(ibc) same with up to 1 cw20?

2023-01-31 22:37 UTC, Buckram123 commented on contracts/croncat-manager/src/balances.rs
> +    if info.funds.len() > 3 {
It should be here then, or limitless if you think it's a bad idea

2023-01-31 22:43 UTC, deveusss commented
> @deveusss lookin good! couple minor things.
> 
> RE: Things @Buckram123 brought up - theres some back in forth in my head about funds for future needs, i would rather support this way to start and remove if need be.

So we are supporting passing funds in instantiate?

2023-01-31 22:43 UTC, deveusss commented
> I personally against attached deposit being the standard way to initialize treasury balance, it doesn't make sense if croncat-factory owner is a croncat-dao itself, why would they ping-pong balance in and out?
> 
> Can't think it can be useful for anything, so I'm more towards blocking attached funds on initialize, at least for now! What's your thoughts on that? @TrevorJTClarke @mikedotexe @NinoLipartiia @deveusss

Whats wrong with passing funds into your contract at init? why not if we have this possibility?

2023-02-01 00:21 UTC, deveusss commented on justfile
> +	yarn go
this is not for CI/CD but for deploy on testnet and check things in testnet

2023-02-01 00:59 UTC, deveusss commented on scripts/deployment/src/manager.ts
> +		const funds:Coin[]=[coin(50,denom)];
√

2023-02-01 01:01 UTC, Buckram123 approved these changes

2023-02-01 01:15 UTC, deveusss commented on contracts/croncat-agents/src/contract.rs
> +        });
this is old code migrated form old contract)))

2023-02-01 04:36 UTC, TrevorJTClarke commented on contracts/croncat-agents/src/contract.rs
> +        AGENT_STATS.remove(deps.storage, agent_id);
Thank you!

2023-02-01 04:45 UTC, TrevorJTClarke commented on contracts/croncat-agents/src/distributor.rs
> +                Ok(agent_tasks_total.into())
So much better!!

2023-02-01 04:46 UTC, TrevorJTClarke approved these changes

2023-02-01 12:39 UTC, merged