Beta/split 0.0.0 tick action
CronCats/cw-croncat pull request #296
Opened 2023-02-01 00:10 UTC by deveusss

2023-02-01 03:04 UTC, mikedotexe requested changes

2023-02-01 03:04 UTC, mikedotexe commented on scripts/deployment/src/manager.ts
> +		const funds:Coin[]=[coin(50,denom)];
What is this for?

2023-02-01 03:29 UTC, mikedotexe commented on scripts/deployment/src/manager.ts
> +		const instRes = await this.client.execute(sender, factoryAddress, deployMsg, executeGas,null,funds);
This line is breaking things, actually, it no longer outputs a correct contract address for the manager contract

<img width="1074" alt="Screen Shot 2023-01-31 at 7 00 42 PM" src="https://user-images.githubusercontent.com/1042667/215938216-3f632184-dcc7-42bb-ab57-af75eb5697f9.png">

2023-02-01 04:55 UTC, TrevorJTClarke commented on contracts/croncat-agents/src/contract.rs
> +    let current_slot = env.block.height;
@mikedotexe dont change to height - the main reason is because we have 2 contexts, block based & time based -- height is restricted to block context and confuses all the things

2023-02-01 04:57 UTC, TrevorJTClarke commented on scripts/deployment/src/manager.ts
> +		const instRes = await this.client.execute(sender, factoryAddress, deployMsg, executeGas,null,funds);
woah - thats very weird & unexpected. Def needs to get removed

2023-02-01 04:58 UTC, TrevorJTClarke commented on contracts/croncat-agents/src/contract.rs
> +    storage: &mut dyn Storage,
agree

2023-02-01 05:04 UTC, TrevorJTClarke commented on contracts/croncat-agents/src/state.rs
> +pub const DEFAULT_AGENTS_EVECT_THRESHOLD: u64 = 600;
`EVECT` - did you mean `EVICT`?

2023-02-01 05:04 UTC, TrevorJTClarke commented on contracts/croncat-agents/src/contract.rs
> +    let current_slot = env.block.height;
Ah i see what you're saying @mikedotexe  - yeah, lets clear that up

2023-02-01 12:42 UTC, deveusss commented on contracts/croncat-agents/src/contract.rs
> +    storage: &mut dyn Storage,
there is a reason, unregister_agent is call in tick, so move occurs, but passing storage resolves that issue)

2023-02-01 12:51 UTC, deveusss commented on contracts/croncat-agents/src/contract.rs
> +    let current_slot = env.block.height;
fixed

2023-02-01 12:52 UTC, deveusss commented on scripts/deployment/src/manager.ts
> +		const funds:Coin[]=[coin(50,denom)];
coins were mandatory, so we updated manager, and coins are not mandatory

2023-02-01 12:52 UTC, deveusss commented on contracts/croncat-agents/src/state.rs
> +pub const DEFAULT_AGENTS_EVECT_THRESHOLD: u64 = 600;
oops) EJECT

2023-02-01 13:20 UTC, deveusss commented on scripts/deployment/src/manager.ts
> +		const instRes = await this.client.execute(sender, factoryAddress, deployMsg, executeGas,null,funds);
it was denom error, validator does not accept ustart in info.funds

2023-02-01 13:27 UTC, deveusss commented on scripts/deployment/src/manager.ts
> +		const instRes = await this.client.execute(sender, factoryAddress, deployMsg, executeGas,null,funds);
fixed

2023-02-01 13:27 UTC, deveusss commented on scripts/deployment/src/manager.ts
> +		const funds:Coin[]=[coin(50,denom)];
fixed

2023-02-02 03:23 UTC, mikedotexe requested changes
Hey @deveusss I see this is in the `UpdateConfig` but not the `InstantiateMsg`. Can we add the `agent_nomination_duration` there, too? And have it save during instantiate. Will be good to keep the initial instantiate message and the updating to be consistent)

2023-02-02 05:18 UTC, mikedotexe commented
I noticed that I am unable to `just build`, `just optimize`, `just deploy` without getting this error:

```
Error: Error when broadcasting tx 0AB8BCC6F9B5A9FA87B1BEA7B020440904F62F66E364DAE96E03BBBFA3E6CF90 at height 3232704. Code: 2; Raw log: failed to execute message; message index: 0: Error calling the VM: Error during static Wasm validation: Wasm contract doesn't have required export: "instantiate". Exports required by VM: ["allocate", "deallocate", "instantiate"].: create wasm contract failed
```

I'm not positive it's this branch, and am checking the BS branch)), but it's taking forever, but thought I'd share here before I forget.

<img width="1044" alt="Screen Shot 2023-02-01 at 9 16 51 PM" src="https://user-images.githubusercontent.com/1042667/216238192-d3037a92-743b-45fe-bf54-595a0fa97985.png">

2023-02-02 11:28 UTC, deveusss commented
> agent_nomination_duration



> Hey @deveusss I see this is in the `UpdateConfig` but not the `InstantiateMsg`. Can we add the `agent_nomination_duration` there, too? And have it save during instantiate. Will be good to keep the initial instantiate message and the updating to be consistent)

hey @mikedotexe its in init too)

https://github.com/CronCats/cw-croncat/blob/beta/split-0.0.0-tick-action/contracts/croncat-agents/src/contract.rs#L52

2023-02-02 17:55 UTC, merged