Small refactor
CronCats/cw-croncat pull request #343
Opened 2023-02-13 16:18 UTC by NinoLipartiia

2023-02-14 13:10 UTC, Buckram123 requested changes
Hey, great start!

2023-02-14 13:10 UTC, Buckram123 commented on contracts/croncat-manager/src/balances.rs
> +        .map_err(StdError::overflow)?;
nice

2023-02-14 13:10 UTC, Buckram123 commented on contracts/croncat-manager/src/helpers.rs
> +        Ok(())
```suggestion
        if addr != *self {
            Err(ContractError::Unauthorized {})
        } else {
            Ok(())
        }
```
looks cleaner this way right?

2023-02-19 22:05 UTC, NinoLipartiia commented on contracts/croncat-manager/src/helpers.rs
> +    ) -> Result<(), ContractError>;
Not sure about this, `ContractError` is defined in croncat-manager, can't use it as the return type, if it's in `croncat-sdk-core`, right?

By the way, why all `ContractError`'s are in the contracts? Can't we move them to `croncat-sdk-core` and import each of them like this:
```
use croncat_sdk_core::internal_messages::manager::ManagerContractError as ContractError;
```

2023-02-20 06:40 UTC, Buckram123 commented on contracts/croncat-manager/src/helpers.rs
> +    ) -> Result<(), ContractError>;
> Not sure about this, `ContractError` is defined in croncat-manager, can't use it as the return type, if it's in `croncat-sdk-core`, right?

You can use `thiserror` `from` attribute to easily handle it

> Can't we move them to croncat-sdk-core

Sure, we can move them, but don't think it can be used outside "Manager" contract or can it?

2023-02-20 06:45 UTC, Buckram123 commented on contracts/croncat-manager/src/helpers.rs
> +    ) -> Result<(), ContractError>;
re(2): or maybe it can be good to move to the responding `sdk` if we implement some types logic and want to return `ContractError`

2023-03-03 22:17 UTC, TrevorJTClarke commented
can you update the conflicts @NinoLipartiia?

2023-03-06 04:11 UTC, closed without merging