Item 6: Validate denom on Manager contract
CronCats/cw-croncat pull request #359
Opened 2023-03-01 22:48 UTC by mikedotexe

We use the query for the bonded denom to validate whether the provided denom is valid.

There were a few cases across other contracts that used hardcoded values that then needed to be updated, as well.

2023-03-01 22:49 UTC, mikedotexe commented on contracts/croncat-manager/src/tests/manager_tests.rs
> +        assert_eq!(manager_balances, Uint128::new(2400));
Note that I took some time to make sure this wasn't just "changing the test to match the output" and indeed verified this tracks.

2023-03-01 23:11 UTC, TrevorJTClarke requested changes
Thanks for doing this!! See comments:

2023-03-01 23:11 UTC, TrevorJTClarke commented on contracts/croncat-agents/src/tests/common.rs
> +/// https://github.com/CosmWasm/cosmwasm/blob/32f308a1a56ae5b8278947891306f7a374c3df94/packages/vm/src/environment.rs#L383
ah nice, was wondering about that!

2023-03-01 23:11 UTC, TrevorJTClarke commented on contracts/croncat-manager/src/contract.rs
> +    let denom = if denom.to_uppercase() != bonded_denom.to_uppercase() {
@mikedotexe the goal is to actually remove instantiate denom, so we only rely on the protocol native denom

2023-03-01 23:11 UTC, TrevorJTClarke commented on contracts/croncat-manager/src/tests/manager_tests.rs
> +        assert_eq!(manager_balances, Uint128::new(2400));
I see the value above, fine w / me

2023-03-01 23:11 UTC, TrevorJTClarke commented on contracts/croncat-manager/src/tests/manager_tests.rs
> +    instantiate_msg.denom = "mochi".to_string();
You did good work on this test - but as per above, i think we shouldn't use instantiate denom

2023-03-01 23:36 UTC, mikedotexe commented on contracts/croncat-manager/src/contract.rs
> +    let denom = if denom.to_uppercase() != bonded_denom.to_uppercase() {
Ah, gotcha

2023-03-02 07:06 UTC, TrevorJTClarke approved these changes
Brilliant!

2023-03-02 18:17 UTC, merged