Item 4: Add whitelist for agent registration
CronCats/cw-croncat pull request #374
Opened 2023-03-05 02:57 UTC by mikedotexe

As per some suggestions, we're introducing an agent registration whitelist. Progressive decentralization makes sense, and will use changes here.

The Agent contract's Config will have a new boolean field `public_registration`.

There's one more piece of state, a `Map` that's being used like a set. It's called `APPROVED_AGENTS`.

A list of approved agents can be provided during instantiation or by calling the new method `add_agent_to_whitelist` which only supports/handles one insertion. For removal, the function `remove_agent_from_whitelist` is introduced. Note that when config updates the `public_registration` from `false` to `true`, the whitelist will be cleared to save space. This is intentionally a one-way boolean, as machinery of safe, controlled, progressive decentralization.

When a prospective agent calls `register_agent`, it fill fail with a new error unless the sender is on the approved list.

2023-03-05 07:07 UTC, TrevorJTClarke requested changes
Looking pretty close! Thanks for the deep dive into this @mikedotexe -- see below

2023-03-05 07:07 UTC, TrevorJTClarke commented on contracts/croncat-agents/src/tests/agent_tests.rs
> +                        agent_address: AGENT0.to_string(),
I missed commenting in the logic side, but it should be noted: Removing from whitelist doesnt remove agent from pending/active queue - and this is intentional. Just means that once they get removed from pending/active, thats it, they cannot register back in

2023-03-05 07:07 UTC, TrevorJTClarke commented on contracts/croncat-agents/src/tests/agent_tests.rs
> +    assert!(
Based on above comment in contract, we'll need 1 more test to cover trying to set it back to False after true. Should fail

2023-03-05 17:27 UTC, mikedotexe commented on packages/croncat-sdk-agents/src/msg.rs
> +pub struct GetApprovedAgentAddresses {
good point, that is silly name for a response. fixed in https://github.com/CronCats/cw-croncat/pull/374/commits/677f58f373e6c51cbf0e110fe0e6d34fe34cd65e

2023-03-05 17:59 UTC, mikedotexe commented on contracts/croncat-agents/src/contract.rs
> +            public_registration: public_registration.unwrap_or(DEFAULT_PUBLIC_REGISTRATION_ENABLED),
You're totally right. Added a new error and logic, and unwrapping or using the config's current value. good eye thanks!
fixed in: https://github.com/CronCats/cw-croncat/pull/374/commits/5db464de14b40934dfed59ddc890f62ddfbb8e2f

2023-03-05 19:51 UTC, mikedotexe commented on contracts/croncat-agents/src/tests/agent_tests.rs
> +                        agent_address: AGENT0.to_string(),
added comment on the Execute method here: https://github.com/CronCats/cw-croncat/pull/374/commits/e368cb006d57ca54701274c0ada2b868d7bc141c

2023-03-05 19:53 UTC, mikedotexe commented on contracts/croncat-agents/src/tests/agent_tests.rs
> +    assert!(
Added in a recent commit from a previous comment: https://github.com/CronCats/cw-croncat/pull/374/commits/5db464de14b40934dfed59ddc890f62ddfbb8e2f

2023-03-06 03:56 UTC, TrevorJTClarke approved these changes

2023-03-06 03:56 UTC, TrevorJTClarke commented on contracts/croncat-agents/src/tests/agent_tests.rs
> +    // Check failure wif admin attempts to "reverse" the public registration from true » false
thank you!

2023-03-06 04:03 UTC, merged