Add `croncat-integration-utils` package, and minor stuffs.
CronCats/cw-croncat pull request #402
Opened 2023-04-12 08:28 UTC by mikedotexe

Created a couple functions here, with the intention of publishing this as a crate integrating dApps can use.

## Create task and handle reply

When you create a task using a submessage with replies, you can utilize two functions in your contract's reply entry point.

1. `reply_handle_task_creation` — this takes the `msg: Reply` argument and parses it into the more useful `CronCatTaskExecutionInfo`, which is just the `croncat-sdk-tasks`'s `TaskExecutionInfo`. It returns this back to the logic in the reply entry point.
2. `reply_complete_task_creation` — this small helper will return data in the response in a more ergonomic way than if we passed the received data along. (It was base64'ing twice)

When implementing the reply end point, contracts can simply call both of these, one after the other. They are split so dApps can add additional logic in the reply execution.

## Handle incoming invocation from a task

In this scenario, your contract is getting called, at a method that we expect to be called by CronCat. We want to know if indeed it's CronCat executing your task, and also check that the task's owner is the receiving contract. If you wish to modify these restrictions, you are able to with this struct for additional parameters:

```rs
pub struct HandleIncomingTaskParams {
    /// Disables the check ensuring that the block height and transaction index are the same
    /// If you expect an IBC delay or something asynchronous, disable by setting to true.
    pub disable_sync_check: bool,
    /// By default, we check that the contract receiving the task invocation
    /// must be the owner of the that task. Put another way: someone else's
    /// task isn't invoking our method. You can disable this by setting to true.
    pub disable_owner_check: bool,
    /// If the owner check is enabled, you may specify an alternate expected owner.
    /// Perhaps the task owner isn't this contract, but you know the address.
    /// By default, the validation logic in `handle_incoming_task` checks against the current contract.
    /// If disable_owner_check is true, this value is irrelevant.
    pub expected_owner: Option<Addr>,
}
```

There is one helper method introduced here:
1. `handle_incoming_task` — this will check the version of the task, and confirm (via a factory query) that the sender is a sanctioned manager contract. It also checks that the execution is happening synchronously by confirming via state that the manager saves right before sending the messages invoking it. Finally, it checks checks that the owner of the task is the receiving contract itself, or else the `expected_owner` provided in the optional parameters.

2023-04-12 16:49 UTC, TrevorJTClarke requested changes
great work man!!
Left a couple minor changes -- but lots of solid progress!

2023-04-12 16:49 UTC, TrevorJTClarke commented on packages/croncat-integration-utils/README.md
> +This repo contains helper methods for projects adding automation to their smart contracts using CronCat tasks.
Can you add the PR comment into this readme? That explainer was great

2023-04-12 16:49 UTC, TrevorJTClarke commented on packages/croncat-integration-utils/src/reply_handler.rs
> +pub fn reply_handle_task_creation(
nice! I think it may be better to explicitly call this: `reply_handle_croncat_task_creation`

2023-04-12 16:49 UTC, TrevorJTClarke commented on packages/croncat-integration-utils/src/reply_handler.rs
> +pub fn reply_complete_task_creation(
Not entirely following why this is needed if the types are available, they can handle how they need.
Maybe better use case somewhere?
Another explicitly named: `reply_data_croncat_task_creation`

2023-04-12 16:49 UTC, TrevorJTClarke commented on packages/croncat-integration-utils/src/handle_incoming_task.rs
> +    querier: &QuerierWrapper,
curious why you chose this over deps?

2023-04-12 16:49 UTC, TrevorJTClarke commented on packages/croncat-integration-utils/src/handle_incoming_task.rs
> +    let versions = latest_task_execution
nice - yeah still been thinking on why we ever did string... lol someday that can change

2023-04-12 16:49 UTC, TrevorJTClarke commented on packages/croncat-integration-utils/src/handle_incoming_task.rs
> +    let mut state_key =
this is great!

2023-04-12 16:49 UTC, TrevorJTClarke commented on packages/croncat-integration-utils/src/handle_incoming_task.rs
> +    let quoted_sender = format!(r#""{}""#, sender);
interesting - is that because of how raw escapes things?

2023-04-12 16:49 UTC, TrevorJTClarke commented on packages/croncat-integration-utils/src/handle_incoming_task.rs
> +    if !disable_sync_check {
egggselllent

2023-04-12 16:49 UTC, TrevorJTClarke commented on packages/croncat-integration-utils/src/handle_incoming_task.rs
> +    if !disable_owner_check && latest_task_execution.owner_addr != owner {
w00t

2023-04-14 16:13 UTC, mikedotexe commented on Cargo.toml
> +cosmwasm-storage = "1.2.3"
Good eye, as mentioned offline, have to remove cosmwasm-storage, and have borrowed a couple functions instead

2023-04-14 16:16 UTC, mikedotexe commented on packages/croncat-integration-utils/src/handle_incoming_task.rs
> +    let quoted_sender = format!(r#""{}""#, sender);
yeah when you deserialize/decode it comes back as `"value"` instead of `value` so wrap it in quotes, and yeah need double-double quotes, animal-style.

2023-04-15 06:47 UTC, TrevorJTClarke commented on justfile
> +		cosmwasm/workspace-optimizer:0.12.12
careful here - this tiny version bump has controversy on OS support

2023-04-20 16:45 UTC, mikedotexe commented on packages/croncat-integration-utils/README.md
> +This repo contains helper methods for projects adding automation to their smart contracts using CronCat tasks.
done! did this for the other packages, too.

for some reason I can tease the writing muse when making a pull request description easier than sitting and writing the README. Maybe I'll use this tactic going forward. I hope myself doesn't find out about it.

2023-04-20 16:50 UTC, mikedotexe commented on packages/croncat-integration-utils/src/reply_handler.rs
> +pub fn reply_complete_task_creation(
Removed this in favor of returning a tuple from `reply_handle_croncat_task_creation`

2023-04-20 18:49 UTC, mikedotexe commented on packages/croncat-integration-utils/src/handle_incoming_task.rs
> +    querier: &QuerierWrapper,
We don't use the storage, and think people will familiar with CronCat might be more at ease knowing that we're not touching their storage

2023-04-20 18:49 UTC, mikedotexe commented on packages/croncat-integration-utils/src/handle_incoming_task.rs
> +    let versions = latest_task_execution
😇 
🚀

2023-04-20 18:50 UTC, mikedotexe commented on packages/croncat-integration-utils/src/handle_incoming_task.rs
> +    let quoted_sender = format!(r#""{}""#, sender);
So I took Vectis's advice and made this much simpler, no longer need this and am doing it from storage more directly.

2023-04-20 18:52 UTC, mikedotexe commented on justfile
> +		cosmwasm/workspace-optimizer:0.12.12
good eye, update to workspace-optimizer:0.12.13 here: https://github.com/CronCats/cw-croncat/pull/402/commits/95bf365469b3e728e5ab80354dc6ee38a51cea26

2023-04-26 20:01 UTC, TrevorJTClarke approved these changes
huge home run sir. TYSM!
well doxxed, well thought out setup.

2023-04-26 20:01 UTC, TrevorJTClarke commented on justfile
> +		cosmwasm/workspace-optimizer:0.12.13
can confirm 0.12.13 works on my OS version. phew!

2023-04-26 20:04 UTC, mikedotexe commented on .github/workflows/Basic.yml
> +          for PACKAGE in $(cargo metadata --format-version 1 --no-deps | jq '.packages[] | .name' -r)
I have a friend named Gary Petunia Thielson that helped me

2023-04-26 20:55 UTC, mikedotexe commented
Made exact version so we don't accidentally use cosmwasm-std 1.2.x since that's not deployed to many blockchains.

The lockfile has an update that's 1.2.x but it's for a proc macro:
https://github.com/CosmWasm/cosmwasm/blob/v1.2.4/packages/derive/Cargo.toml

2023-05-01 19:53 UTC, TrevorJTClarke commented
Where are we at with this? Are you hoping to merge and release? or wait until something?

2023-05-02 20:33 UTC, mikedotexe commented on integration-sdk/croncat-errors-macro/src/lib.rs
> +        let msg = "😻 Please move the `#[croncat_error]` macro above the `#[derive]` attribute with the `Error` trait. 😻";
Correct, when they go to compile their contract it'll say, "Couldn't compile because of an error" and they scroll up and see the cute cat emojis that tell them exactly what to do.

2023-05-02 20:39 UTC, mikedotexe commented on integration-sdk/croncat-integration-utils/src/reply_handler.rs
> +pub fn reply_handle_croncat_task_creation(
I know I've had a few moments where I'm like, "dang it, I have the bytes, how the hell do I turn this into my struct again? oh yeahhh, that `serde_json_wasm`, forgot about that.

I also rarely use `cw_utils` and it doesn't exist in any of the examples.

Basically making things easy, zero cognitive overhead for projects that wish to use CronCat

2023-05-02 20:52 UTC, mikedotexe commented on integration-sdk/croncat-integration-utils/src/task_creation.rs
> +    let latest_contract_res: ContractMetadataResponse =
Agree this is good to do but not urgent. Given our offline convo today, would like to march forward, having captured this in this ticket: https://github.com/CronCats/cw-croncat/issues/409

2023-05-02 21:07 UTC, mikedotexe commented on integration-sdk/croncat-integration-utils/src/tests/mod.rs
> +
I've thought about this a bit as well.

In terms of the CronCat product, I believe the only thing these integration crates are doing is *using* what exists and is merged into the codebase. Example of an existing test for the TaskExecutionInfo check during incoming invocation: https://github.com/CronCats/cw-croncat/blob/beta-0.1.5/contracts/croncat-manager/src/tests/manager_tests.rs#L5361

`cw-multi-test` is slightly limited in certain kinds of robusts tests involving multiple transactions in a block, so I added this issue after Simon referred me here from another issue I created: https://github.com/CosmWasm/cw-multi-test/issues/36

Mentally, I came back to the topic of test coverage for this, and couldn't convince myself of its importance.

Here's an example from the (slightly more complicated) example "create a tick task to myself and make sure no one else can call me at this method" here, showing the full flow of deploying an integrating dApp and handling the reply correctly: https://github.com/CronCats/cw-purrbox/blob/main/contracts/create-task-handle-tick/src/tests/create_task_handle_tick.rs#L104

Here's another test in that same file that adds an agent and proxy call into the mix: https://github.com/CronCats/cw-purrbox/blob/main/contracts/create-task-handle-tick/src/tests/create_task_handle_tick.rs#L247

2023-05-02 21:08 UTC, mikedotexe commented on packages/croncat-sdk-tasks/src/types.rs
> +    /// \[X,Y,Z\] to reach that value
`cargo doc` told me to

2023-05-03 03:16 UTC, merged