Refactoring scripts
CronCats/cw-croncat pull request #58
Opened 2022-08-10 16:06 UTC by deveusss

2022-08-16 17:36 UTC, deveusss reviewed
Added more scripts

2022-08-16 17:42 UTC, Buckram123 requested changes

2022-08-16 17:42 UTC, Buckram123 commented on contracts/cw-croncat/scripts/testnet_create_recurring_task.sh
> +. ./testnet_init_vars.sh
```suggestion
#!/bin/bash
. ./testnet_init_vars.sh
```

2022-08-16 17:42 UTC, Buckram123 commented on contracts/cw-croncat/scripts/testnet_create_staking_task.sh
> +. ./testnet_init_vars.sh
```suggestion
#!/bin/bash
. ./testnet_init_vars.sh
```

2022-08-16 17:42 UTC, Buckram123 commented on contracts/cw-croncat/scripts/testnet_deploy.sh
> +sh ../build.sh
```suggestion
```
No reason to build it right before building with docker (the only difference is clippy) and extra time

2022-08-16 17:42 UTC, Buckram123 commented on contracts/cw-croncat/scripts/testnet_get_agent_ids.sh
> +. ./testnet_init_vars.sh
```suggestion
#!/bin/bash
. ./testnet_init_vars.sh
```

2022-08-16 17:42 UTC, Buckram123 commented on contracts/cw-croncat/scripts/testnet_get_agent_tasks.sh
> +. ./testnet_init_vars.sh
```suggestion
#!/bin/bash
. ./testnet_init_vars.sh
```

2022-08-16 17:42 UTC, Buckram123 commented on contracts/cw-croncat/scripts/testnet_get_contract_info.sh
> +. ./testnet_init_vars.sh
```suggestion
#!/bin/bash
. ./testnet_init_vars.sh
```

2022-08-16 17:42 UTC, Buckram123 commented on contracts/cw-croncat/scripts/testnet_get_tasks.sh
> +. ./testnet_init_vars.sh
```suggestion
#!/bin/bash
. ./testnet_init_vars.sh
```

2022-08-16 17:42 UTC, Buckram123 commented on contracts/cw-croncat/scripts/testnet_init_vars.sh
> +NODE="--node https://rpc.uni.juno.deuslabs.fi:443"
```suggestion
#!/bin/bash
NODE="--node https://rpc.uni.juno.deuslabs.fi:443"
```

2022-08-16 17:42 UTC, Buckram123 commented on contracts/cw-croncat/scripts/testnet_query_agents.sh
> +. ./testnet_init_vars.sh
```suggestion
#!/bin/bash
. ./testnet_init_vars.sh
```

2022-08-16 17:42 UTC, Buckram123 commented on contracts/cw-croncat/scripts/testnet_reg_and_proxy_call.sh
> +. ./testnet_init_vars.sh
```suggestion
#!/bin/bash
. ./testnet_init_vars.sh
```

2022-08-16 17:42 UTC, Buckram123 commented on contracts/cw-croncat/scripts/testnet_unregister_agent.sh
> +. ./testnet_init_vars.sh
```suggestion
#!/bin/bash
. ./testnet_init_vars.sh
```

2022-08-16 18:07 UTC, Buckram123 approved these changes
Nice

2022-08-16 18:14 UTC, Buckram123 approved these changes

2022-08-16 18:17 UTC, Buckram123 approved these changes

2022-08-16 18:19 UTC, NinoLipartiia approved these changes

2022-08-16 18:20 UTC, Buckram123 approved these changes

2022-08-19 21:48 UTC, mikedotexe commented on contracts/cw-croncat/scripts/testnet_create_staking_task.sh
> +CONTRACT=juno12z4hh9r3j9aurjn6ppkgyjrkuu4ugrdectsh792w8feyj56dhlssvntdls
Eventually, would be great to have these be given as parameters, like here:
https://www.redhat.com/sysadmin/arguments-options-bash-scripts
See the section on "Positional parameters"

2022-08-19 21:49 UTC, mikedotexe approved these changes

2022-08-19 21:51 UTC, deveusss commented on contracts/cw-croncat/scripts/testnet_create_staking_task.sh
> +CONTRACT=juno12z4hh9r3j9aurjn6ppkgyjrkuu4ugrdectsh792w8feyj56dhlssvntdls
good point)

2022-08-19 21:51 UTC, mikedotexe approved these changes

2022-08-19 21:52 UTC, merged