Rules with balances
CronCats/cw-croncat pull request #67
Opened 2022-08-15 17:10 UTC by NinoLipartiia

Closes #61

2022-08-15 17:16 UTC, NinoLipartiia commented
I'm not sure if HasBalance should be split in two methods: HasBalanceNative and HasBalanceCw20?

2022-08-15 19:10 UTC, Buckram123 requested changes
Hey! Good job, few nits. I agree with you about splitting `Has` to two methods `HasBalance` and `HasCw20Balance`

2022-08-15 19:10 UTC, Buckram123 commented on contracts/cw-rules/src/contract.rs
> +    };
```suggestion
let res = match (balance, required_balance) {
        (Balance::Native(current), Balance::Native(expected)) => {
            expected.0.iter().all(|c| has_coins(&current.0, c))
        }
        (Balance::Cw20(current_cw20), Balance::Cw20(expected_cw20)) => {
            current_cw20.address == expected_cw20.address
                && current_cw20.amount >= expected_cw20.amount
        }
        _ => false,
    };
```
little bit more compact

2022-08-19 10:29 UTC, Buckram123 approved these changes

2022-08-19 10:36 UTC, merged