Agent nomination feature
CronCats/cw-croncat pull request #7
Opened 2022-05-10 06:43 UTC by mikedotexe

This PR fleshes out the "agent nomination" process. When a task is added, sometimes the new number of tasks exceed the task ratio and a new agent can join. The agent who wishes to join has already registered as an agent, and is placed in the pending queue.

The moment that task (discussed previously) is added, a timestamp is set for when agent nominations are open.
There is a "duration" given for the first person in line. Once that duration has passed, the second person in the queue is allowed to "nominate themself" and be added as an active agent, and removed as a pending agent.

If the second person in line succeeds at nominating themself, everyone before them in line are removed from the pending queue, as they seem to be offline. They will need to re-register and get back in line.

2022-05-10 06:45 UTC, mikedotexe commented
There were a few items Trevor and I discussed on a call today, and these are not yet added but will be. I wanted to give the opportunity for a head start. 

Items:

- [ ] agent_nomination_duration be optional with default value
- [ ] agent state should not change during accept_nomination_agent, just use queues
- [ ] check ContractError::CustomError and replace with UnregisterSomething instead

2022-05-12 00:08 UTC, TrevorJTClarke requested changes
@mikedotexe lots of great work here! See comments inline :) YOU ROCK!!!!

2022-05-12 00:08 UTC, TrevorJTClarke commented on contracts/cw-croncat/src/agent.rs
> +        assert_eq!(num_tasks, 3);
I believe this should be 4.
Thoughts on this behaviour: 
ratio of 1:2, means entry upon >= 1:2 - so there is 1 agent doing up to 3 tasks before onboarding new agent. The task total would reach 4 tasks before adding another agent.
My main thinking here was to keep the agent profitable as a preference. More tasks is better for agents

2022-05-12 00:08 UTC, TrevorJTClarke commented on contracts/cw-croncat/src/agent.rs
> +        register_agent_exec(&mut app, &contract_addr, AGENT4, &AGENT_BENEFICIARY);
@mikedotexe this brings up a good point - if an agent registers and there are more than enough tasks to support them becoming active - do they skip the pending queue? Do they get put into the pending queue if pending queue is empty?

2022-05-12 00:08 UTC, TrevorJTClarke commented on contracts/cw-croncat/src/tasks.rs
> +        let total_tasks = self
@mikedotexe see other comments about the https://github.com/CronCats/cw-croncat/blob/main/contracts/cw-croncat/src/state.rs#L100 field & method - this should be incremented in this fn if it isnt already

2022-05-17 04:55 UTC, mikedotexe commented on packages/cw-croncat-core/src/types.rs
>      pub register_start: u64,
sure thing, just pushed it up

2022-05-17 05:14 UTC, mikedotexe commented on contracts/cw-croncat/src/agent.rs
> +        } else if active.contains(&account_id) {
good thought, just pushed up a commit addressing this https://github.com/CronCats/cw-croncat/pull/7/commits/eab3a31ad54278c00fdd73639d5ad71aa8ea942b

2022-05-17 05:16 UTC, mikedotexe commented on contracts/cw-croncat/src/agent.rs
> +            return Err(StdError::GenericErr {
Gotcha. The note about the IDE is because I'm using CLion and this is the first time I've experienced the IDE having red-underlines around this. It threw me for a loop trying to fix something that wasn't wrong. Thought I'd point it out for future devs who may see the same thing.

2022-05-17 05:38 UTC, mikedotexe commented on contracts/cw-croncat/src/agent.rs
> +            return Err(StdError::GenericErr {
Added the error in this commit https://github.com/CronCats/cw-croncat/pull/7/commits/6443161259793f87fb98aa5d0fc5a7585859ab89

2022-05-17 17:29 UTC, mikedotexe commented on contracts/cw-croncat/src/agent.rs
> +            let total_tasks = self
Good idea, pushed up change in https://github.com/CronCats/cw-croncat/pull/7/commits/7b5c3fb102276c756d3eb9afd0a5ab602307e376

2022-05-19 06:44 UTC, mikedotexe commented on contracts/cw-croncat/src/agent.rs
> +            if total_tasks as u64 > num_active_agents as u64 * task_ratio[0] * task_ratio[1]
Split this into a helper and added a test for it here: https://github.com/CronCats/cw-croncat/pull/7/commits/1c06385708d81830a69381f4f9a34ea7524c2f6b

It was interesting to not use `app` in the tests at all for this one.

2022-05-19 15:39 UTC, mikedotexe commented on contracts/cw-croncat/src/agent.rs
> +            return Err(ContractError::Unauthorized {});
Good call, changed here: https://github.com/CronCats/cw-croncat/pull/7/commits/4895ac516eec483e82aa4116d8c792ba03c2f19e

2022-05-19 19:09 UTC, mikedotexe commented on contracts/cw-croncat/src/agent.rs
> +        assert_eq!(num_tasks, 3);
Interesting, thanks for talking that through on Element. As we discussed, I've changed the task ratio to be a single number that represents the maximum tasks an agent can do.
See: https://github.com/CronCats/cw-croncat/pull/7/commits/8fe414dd0d2d2cface528f749c2f6e256aa9c141

2022-05-23 15:52 UTC, mikedotexe commented on contracts/cw-croncat/src/tasks.rs
> +        let total_tasks = self
Good eye. I just realized I called that earlier in the function so am reusing it. Saw it with fresh eyes today.
See https://github.com/CronCats/cw-croncat/pull/7/commits/6557ad98f00d04a9c2232b3bb982f38d8c53bba3

2022-05-24 17:30 UTC, TrevorJTClarke approved these changes
@mikedotexe throwing an approve on this - minor couple things in there if you have a minute :) Otherwise you rocked it!! :D

2022-05-24 17:30 UTC, TrevorJTClarke commented on contracts/cw-croncat/src/state.rs
> +    pub max_tasks_per_agent: u64,
@mikedotexe i think it should actually be `min_tasks_per_agent`, because thats the minimum of new tasks needed before onboarding another agent. Thoughts?

2022-05-24 17:30 UTC, TrevorJTClarke commented on contracts/cw-croncat/src/tasks.rs
> +        size += 1;
@mikedotexe let's change to reuse this: https://github.com/CronCats/cw-croncat/blob/main/contracts/cw-croncat/src/state.rs#L104

2022-05-24 17:30 UTC, TrevorJTClarke commented on contracts/cw-croncat/src/helpers.rs
> +    pub fn agents_to_let_in(
luvvit!

2022-05-24 17:30 UTC, TrevorJTClarke commented on contracts/cw-croncat/src/helpers.rs
> +        // block_time: u64,
remove?

2022-05-24 17:30 UTC, TrevorJTClarke commented on contracts/cw-croncat/src/helpers.rs
> +    ) -> Result<AgentStatus, ContractError> {
nice work!

2022-05-24 17:30 UTC, TrevorJTClarke commented on contracts/cw-croncat/src/agent.rs
> +                            register_start: env.block.time,
Does this need to be `.seconds()`?

2022-05-26 02:29 UTC, mikedotexe commented on contracts/cw-croncat/src/state.rs
> +    pub max_tasks_per_agent: u64,
Yeah, I agree. I suppose in my mind I thought it was "max tasks per agent for the system to allow someone in" but I've crammed more context in there than is clear from that name. Fixed here:
https://github.com/CronCats/cw-croncat/pull/7/commits/7270600b8f991066d35c8e10de13919fd96b5119

2022-05-26 02:37 UTC, mikedotexe commented on contracts/cw-croncat/src/tasks.rs
> +        size += 1;
Good stuff.
https://github.com/CronCats/cw-croncat/pull/7/commits/cadd6f4b9e9fd663f35bd0f605cc8e679fd41aa8

2022-05-26 02:38 UTC, mikedotexe commented on contracts/cw-croncat/src/helpers.rs
> +        // block_time: u64,
Ah yes:
https://github.com/CronCats/cw-croncat/pull/7/commits/10179489334f998383e77d7cd9bfbac0e4ddbcb8

2022-05-26 02:55 UTC, mikedotexe commented on contracts/cw-croncat/src/agent.rs
> +                            register_start: env.block.time,
So this type was changed to `Timestamp` actually here:
https://github.com/CronCats/cw-croncat/blob/10179489334f998383e77d7cd9bfbac0e4ddbcb8/packages/cw-croncat-core/src/types.rs#L45-L49

```rs
pub struct Agent {
    …

    // Timestamp of when agent first registered
    // Useful for rewarding agents for their patience while they are pending and operating service
    // Agent will be responsible to constantly monitor when it is their turn to join in active agent set (done as part of agent code loops)
    // Example data: 1633890060000000000 or 0
    pub register_start: Timestamp,
}
```

Would you prefer it be a `u64`?

2022-05-26 16:09 UTC, TrevorJTClarke commented on contracts/cw-croncat/src/agent.rs
> +                            register_start: env.block.time,
Ah i see - the context was lost in the implementation in review. Keep it, thanks

2022-05-26 19:35 UTC, merged