Fix balance methods in cw_rules
CronCats/cw-croncat pull request #77
Opened 2022-08-23 16:00 UTC by NinoLipartiia

Changed `query_has_balance` and `query_get_cw20_balance` so that they return `Coin` in `Binary`.
Renamed `query_has_balance` to `query_has_balance_gt` and implemented checking that the given address has more coins than the given balance.

Also I'm not sure whether `query_get_cw20_balance` should return `Coin`.  I think `Cw20CoinVerified` is more suitable as it has `address` instead of `denom`:
```
pub struct Cw20CoinVerified {
    pub address: Addr,
    pub amount: Uint128,
}
```
Another option is to return `Balance` in both `query_has_balance` and `query_get_cw20_balance`
```
pub enum Balance {
    Native(NativeBalance),
    Cw20(Cw20CoinVerified),
}
```

2022-08-23 16:59 UTC, Buckram123 requested changes
Hey, good job on fixing query balances methods. Agree that `query_get_cw20_balance` should return `Cw20CoinVerified`

2022-08-23 16:59 UTC, Buckram123 commented on contracts/cw-rules/src/msg.rs
> +    HasBalanceGT {
I think we want here `HasBalanceGt`, because snake_cased version of it will be `has_balance_g_t`, instead of `has_balance_gt`

2022-08-23 16:59 UTC, Buckram123 commented on contracts/cw-rules/src/contract.rs
> +            has_balance
```suggestion
            required_vec.iter().all(|required| has_coins(&balances, required))
```

2022-08-24 10:23 UTC, NinoLipartiia commented on contracts/cw-rules/src/contract.rs
> +            has_balance
Changed it to
```
required_vec.iter().all(|required| {
    required.amount == Uint128::zero() || has_coins(&balances, required)
})
```
to cover a case when required balance is zero

2022-09-06 08:52 UTC, Buckram123 approved these changes

2022-09-06 17:09 UTC, mikedotexe commented on contracts/cw-rules/src/contract.rs
> +fn query_has_balance_gt(
👍🏼

2022-09-06 17:22 UTC, mikedotexe commented on contracts/cw-rules/src/contract.rs
> +                required.amount == Uint128::zero() || has_coins(&balances, required)
I also think we may want to make a small change so the function name is `query_has_balance_gte` (for greater-than-or-equal) since we're using `>=` here, and so does `has_coins`

2022-09-07 12:53 UTC, NinoLipartiia commented on contracts/cw-rules/src/contract.rs
> +                required.amount == Uint128::zero() || has_coins(&balances, required)
If you query "you must have 19 ujuno", then `required.amount` is 19, so it won't return true.

`required.amount == Uint128::zero()` is here for the case when you query "you must have at least 0 ujuno", then it should return true, even if address doesn't have any ujuno.

2022-09-08 21:02 UTC, mikedotexe requested changes

2022-09-08 21:02 UTC, mikedotexe commented on contracts/cw-rules/src/contract.rs
> +    let balance_response: BalanceResponse = deps
Actually, can we also `addr_validate` the `address`? I think it'll be best to validate both the `cw20_contract` and that, otherwise people may get odd errors.

2022-09-08 21:03 UTC, mikedotexe commented on contracts/cw-rules/src/contract.rs
> +    let balance_response: BalanceResponse = deps
Other than that, this is looking amazing, and wonderful job with the tests as usual

2022-09-08 21:14 UTC, mikedotexe commented on contracts/cw-rules/src/contract.rs
> +    let balance_response: BalanceResponse = deps
actually, let's just have this be a covered in this smaller ticket https://github.com/CronCats/cw-croncat/issues/86

2022-09-08 21:15 UTC, mikedotexe approved these changes

2022-09-08 21:15 UTC, merged